/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.11
 * Generated at: 2023-02-10 09:06:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class jsp_005fheader_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("file:/C:/Users/Admin/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar", Long.valueOf(1666169782746L));
    _jspx_dependants.put("jar:file:/C:/Users/Admin/.m2/repository/org/springframework/spring-webmvc/4.3.7.RELEASE/spring-webmvc-4.3.7.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1488353688000L));
    _jspx_dependants.put("file:/C:/Users/Admin/.m2/repository/org/springframework/spring-webmvc/4.3.7.RELEASE/spring-webmvc-4.3.7.RELEASE.jar", Long.valueOf(1666169773704L));
    _jspx_dependants.put("jar:file:/C:/Users/Admin/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153381482000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" media=\"all\" href=\"css/dataTable.css\">\n");
      out.write("<style>\n");
      out.write("    #gridListNotifications table thead > tr th:nth-child(1),\n");
      out.write("    #gridListNotifications table tbody > tr td:nth-child(1){\n");
      out.write("        width: 30%!important;\n");
      out.write("    }\n");
      out.write("    #gridListNotifications table thead > tr th:nth-child(2),\n");
      out.write("    #gridListNotifications table tbody > tr td:nth-child(2){\n");
      out.write("        width: 70%!important;\n");
      out.write("    }\n");
      out.write("    #gridListNotifications table  tbody {\n");
      out.write("        flex: 1 1 auto;\n");
      out.write("        width: 100%;\n");
      out.write("        overflow-y: scroll;\n");
      out.write("        overflow-x: hidden;\n");
      out.write("        min-height: 200px;\n");
      out.write("        max-height: 200px;\n");
      out.write("        height:auto !important;\n");
      out.write("    }\n");
      out.write("    #gridListNotifications table {\n");
      out.write("        display: flex;\n");
      out.write("        flex-flow: column;\n");
      out.write("        height: 100%;\n");
      out.write("        width: 100%;\n");
      out.write("    }\n");
      out.write("    #gridListNotifications table thead, #gridListNotifications table tbody tr {\n");
      out.write("        display: table;\n");
      out.write("        table-layout: fixed;\n");
      out.write("    }\n");
      out.write("    #gridListNotifications table thead {\n");
      out.write("        width: calc(100% -  6px) !important;\n");
      out.write("        flex: 0 0 auto;\n");
      out.write("    }\n");
      out.write("    #gridListNotifications table tbody tr {\n");
      out.write("        width: 100%;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    #gridListNotifications table > tbody > tr > td,\n");
      out.write("    #gridListNotifications table > tbody > tr > th,\n");
      out.write("    #gridListNotifications table > tfoot > tr > td,\n");
      out.write("    #gridListNotifications table > tfoot > tr > th,\n");
      out.write("    #gridListNotifications table > thead > tr > td,\n");
      out.write("    #gridListNotifications table > thead > tr > th {\n");
      out.write("        padding: 5px;\n");
      out.write("        font-size: 12px;\n");
      out.write("    }\n");
      out.write("    .global_breadcrumbs>li{\n");
      out.write("        text-align: center;\n");
      out.write("        justify-content: center;\n");
      out.write("        width: 100%;\n");
      out.write("    }\n");
      out.write("</style>\n");
      out.write("<header class=\"header\">\n");
      out.write("    <div style=\"width: 7vw;\">\n");
      out.write("        <h1 style=\" text-align: right; color: white; font-size: 25px;\">\n");
      out.write("            <small style=\" color: white;font-size:20px;\">CliniSys<span style=\" color: rgb(215, 214, 214);\">Erp</span>\n");
      out.write("            </small>\n");
      out.write("        </h1>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"nameModule hidden-xs\" style=\" width: 50vw;\">\n");
      out.write("        <h1 style=\" text-align: right; color: white; margin-top: 5px; display: inline-block;\">\n");
      out.write("            <small style=\" color: white;\"><span id=\"titleModule\"></span></small>\n");
      out.write("        </h1>\n");
      out.write("        <div class=\"global_breadcrumbs\" style=\"width: 50%;\"></div>                \n");
      out.write("    </div>\n");
      out.write("    <div class=\"hidden-xs\" style=\"width: 18vw;\">\n");
      out.write("        <div id=\"logout\" class=\"btn-header transparent pull-right\">\n");
      out.write("            <span> <a data-action=\"logout\" id=\"globaldeconnexion\" href=\"logout\"><i\n");
      out.write("                        class=\"fas fa-power-off\"></i></a> </span>\n");
      out.write("<!--            <div id=\"refresh\" class=\"btn-header transparent pull-right\">\n");
      out.write("                <span> <a data-action=\"refresh\"  href=\"menu\"><i class=\"fa fa-exchange-alt\" ></i></a> </span>\n");
      out.write("            </div>-->\n");
      out.write("        </div>        <div id=\"fullscreen\" class=\"btn-header transparent pull-right\">\n");
      out.write("            <span> <a href=\"javascript:void(0);\" id=\"globalpleinEcran\"><i class=\"fas fa-arrows-alt\"></i></a> </span>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <div id=\"acceuil\" class=\"btn-header transparent pull-right\">\n");
      out.write("            <span> <a data-action=\"acceuil\" id=\"globalAcceuil\"><i class=\"fas fa-home\"></i></a> </span>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div id=\"userAffiche\" class=\"btn-header transparent pull-right\" style=\"\">\n");
      out.write("            <span name=\"_user\" class=\"\" style=\"margin-top: 8px;color: white;display: inline-block;\">\n");
      out.write("                <span style=\"font-size: 17px; font-family: serif;\">\n");
      out.write("                    <i class=\"fas fa-user\"></i>\n");
      out.write("                    <span id=\"userName\"></span>\n");
      out.write("                </span>\n");
      out.write("            </span>\n");
      out.write("        </div>     \n");
      out.write("\n");
      out.write("    </div> \n");
      out.write("<!--    <div class=\"hidden-xs\" style=\"width: 25vw;\">\n");
      out.write("        <h1 style=\"text-align: right;color: white;margin-top: 5px;display: inline-block; margin-left:10px; \">\n");
      out.write("            <small style=\" color: white;\"> <span id=\"societe\"> </span><span id=\"exercice\"></span></small>\n");
      out.write("        </h1> \n");
      out.write("\n");
      out.write("    </div>     -->\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "body_page/EditionModal.jsp", out, false);
      out.write(" \n");
      out.write("\n");
      out.write("</header>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
