/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.11
 * Generated at: 2023-02-10 09:06:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.master_005fpage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("file:/C:/Users/Admin/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar", Long.valueOf(1666169782746L));
    _jspx_dependants.put("jar:file:/C:/Users/Admin/.m2/repository/org/springframework/spring-webmvc/4.3.7.RELEASE/spring-webmvc-4.3.7.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1488353688000L));
    _jspx_dependants.put("file:/C:/Users/Admin/.m2/repository/org/springframework/spring-webmvc/4.3.7.RELEASE/spring-webmvc-4.3.7.RELEASE.jar", Long.valueOf(1666169773704L));
    _jspx_dependants.put("jar:file:/C:/Users/Admin/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153381482000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005feval_0026_005fvar_005fexpression_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fspring_005feval_0026_005fvar_005fexpression_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fspring_005feval_0026_005fvar_005fexpression_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.release();
    _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write(" \n");
      if (_jspx_meth_spring_005feval_005f0(_jspx_page_context))
        return;
      out.write('\n');
      if (_jspx_meth_spring_005feval_005f1(_jspx_page_context))
        return;
      out.write('\n');
      if (_jspx_meth_spring_005feval_005f2(_jspx_page_context))
        return;
      out.write('\n');
      if (_jspx_meth_spring_005feval_005f3(_jspx_page_context))
        return;
      out.write('\n');
      if (_jspx_meth_spring_005feval_005f4(_jspx_page_context))
        return;
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html  style=\"overflow: hidden!important;\">\n");
      out.write("    <head>  \n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>Facturation</title>\n");
      out.write("        <meta name=\"description\" content=\"\">\n");
      out.write("        <meta name=\"author\" content=\"\"> \n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no\">\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../body_page/css_declare.jsp", out, false);
      out.write("\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" media=\"all\" href=\"css/menu.css\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" media=\"all\" href=\"css/menuCsys.css\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" media=\"all\" href=\"css/styleCsys.css\">\n");
      out.write("        <style>\n");
      out.write("            .demo{\n");
      out.write("                visibility:hidden !important;\n");
      out.write("            }\n");
      out.write("            @media all and (max-device-width: 768px) \n");
      out.write("            {\n");
      out.write("                #width_image\n");
      out.write("                {\n");
      out.write("                    width: 90% !important;\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            @media screen and (min-width: 1200px) \n");
      out.write("            {\n");
      out.write("                #width_image\n");
      out.write("                {\n");
      out.write("                    width: 50% !important;\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("            .ajax-dropdown:after,\n");
      out.write("            .ajax-dropdown:before{\n");
      out.write("                left: 67%;\n");
      out.write("            }\n");
      out.write("            .dropdown-menu {\n");
      out.write("                background-color: #EFEFEF;\n");
      out.write("                font-family: serif\n");
      out.write("            }\n");
      out.write("            #ribbon > div, #ribbon > div > div{\n");
      out.write("                height : 100%;\n");
      out.write("            }\n");
      out.write("            #ribbon{\n");
      out.write("                position: fixed;\n");
      out.write("                right: 0px;\n");
      out.write("                left: 0px;\n");
      out.write("                bottom: 0px;\n");
      out.write("                top: 38px;\n");
      out.write("            }\n");
      out.write("            .views, .views div{\n");
      out.write("                height:100%;\n");
      out.write("            }\n");
      out.write("            .views div iframe{\n");
      out.write("                height: calc(100% - 9px) !important;\n");
      out.write("            }\n");
      out.write("            #alert{\n");
      out.write("                position: relative;  \n");
      out.write("            }  \n");
      out.write("            #sideAlert {\n");
      out.write("                height: 100%; /* 100% Full-height */\n");
      out.write("                width: 0; /* 0 width - change this with JavaScript */\n");
      out.write("                position: fixed; /* Stay in place */\n");
      out.write("                z-index: 1; /* Stay on top */\n");
      out.write("                top: 0;\n");
      out.write("                right: 0;\n");
      out.write("                background-color: white;\n");
      out.write("                overflow-x: hidden; /* Disable horizontal scroll */\n");
      out.write("                /* Place content 60px from the top */\n");
      out.write("                transition: 1.5s; /* 0.5 second transition effect to slide in the sidenav */\n");
      out.write("                box-shadow: -6px 0px 7px -1px rgba(0,0,0,0.75);\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            #sideAlert b { \n");
      out.write("                position: absolute;\n");
      out.write("                right:0;\n");
      out.write("            }\n");
      out.write("            #sideAlert li { \n");
      out.write("                position: relative;\n");
      out.write("                white-space: nowrap;\n");
      out.write("                padding: 8px 16px;\n");
      out.write("                border-bottom: 1px solid #ddd;\n");
      out.write("                font-weight: 700;\n");
      out.write("            }\n");
      out.write("            #sideAlert ul {\n");
      out.write("                list-style-type: none;\n");
      out.write("                padding: 0;\n");
      out.write("                border: 1px solid #ddd;\n");
      out.write("                padding: 8px 16px;\n");
      out.write("                border-bottom: 1px solid #ddd;\n");
      out.write("\n");
      out.write("            }\n");
      out.write("\n");
      out.write("\n");
      out.write("            #sideAlert ul li:last-child {\n");
      out.write("                border-bottom: none   \n");
      out.write("            }\n");
      out.write("            .global_breadcrumbs {\n");
      out.write("                padding: 8px 15px;\n");
      out.write("                list-style: none;\n");
      out.write("                border-radius: 2px;\n");
      out.write("                display: inline-block;\n");
      out.write("            }\n");
      out.write("            .global_breadcrumbs>li {\n");
      out.write("                display: inline-block;\n");
      out.write("                color: white;\n");
      out.write("            }\n");
      out.write("            .global_breadcrumbs>li+li:before {\n");
      out.write("                content: \"/\\00a0\";\n");
      out.write("                padding: 0 5px;\n");
      out.write("                color: #ccc;\n");
      out.write("            }\n");
      out.write("            .global_breadcrumbs>.active {\n");
      out.write("                color: #999;\n");
      out.write("            }\n");
      out.write("        </style>\n");
      out.write("\n");
      out.write("    </head>\n");
      out.write("    <body class=\"fixed-header styleCsys\" > \n");
      out.write("        ");
      if (_jspx_meth_c_005fimport_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("        <!-- #MAIN PANEL -->\n");
      out.write("        <div id=\"main\" role=\"main\" style=\"height: 616px;\"> \n");
      out.write("            <!-- #MAIN CONTENT -->\n");
      out.write("            <div id=\"ribbon\" style=\" padding-right: 0px; padding-left: 0px;\">\n");
      out.write("                <div class=\"right_col\">\n");
      out.write("                    <div class=\"royal_tab\" data-position=\"top\" data-alignment=\"left\" data-animation=\"slide\" data-keyboard=\"true\"  >\n");
      out.write("                        <div class=\"tabs pull-left\" id=\"tabs\">\n");
      out.write("                            <ul class=\"ui-tabs-nav\">\n");
      out.write("                            </ul>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"views\" >\n");
      out.write("\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div> \n");
      out.write("            <!-- END #MAIN CONTENT --> \n");
      out.write("        </div>\n");
      out.write("        <!-- END #MAIN PANEL --> \n");
      out.write("        <!-- Loading... -->\n");
      out.write("        <div class=\"divMessageBox \" id=\"MsgLoading\" style=\"display: none;\">\n");
      out.write("            <div class=\"MessageBoxContainer \" id=\"Msg1\">\n");
      out.write("                <div class=\"MessageBoxMiddle\">\n");
      out.write("                    <span class=\"MsgTitle\">\n");
      out.write("                        <i class=\"fa fa-refresh fa-spin\" style=\"color:green\"></i>");
      if (_jspx_meth_spring_005fmessage_005f0(_jspx_page_context))
        return;
      out.write(" \n");
      out.write("                    </span>\n");
      out.write("                    <p class=\"pText\"></p>\n");
      out.write("                    <div class=\"MessageBoxButtonSection\">\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div id=\"testExit\" style=\"display: none;\">false</div>\n");
      out.write("        <div id=\"pageDest\" style=\"display: none;\"></div>\n");
      out.write("        <!-- END Loading... -->\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../body_page/js_declare.jsp", out, false);
      out.write("\n");
      out.write("        <script>\n");
      out.write("            var url_base = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url_base}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\n");
      out.write("            var idModule = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${idModule}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\n");
      out.write("            var url_base_access = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url_base_access}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\n");
      out.write("            var currencyScale = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${currencyScale}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\n");
      out.write("              var url_base_fichier_base = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url_base_fichier_base}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\n");
      out.write("            if (localStorage.getItem(\"langue\") === \"ar\") {\n");
      out.write("                let url = \"css/AR.css\";\n");
      out.write("                let head = document.getElementsByTagName(\"head\")[0];\n");
      out.write("                let link = document.createElement(\"link\");\n");
      out.write("                link.type = \"text/css\";\n");
      out.write("                link.rel = \"stylesheet\";\n");
      out.write("                link.href = url;\n");
      out.write("                head.appendChild(link);\n");
      out.write("            }\n");
      out.write("//            $(document).ready(function (e) {\n");
      out.write("//                if (window.sessionStorage.getItem('Exercice') === null || window.sessionStorage.getItem('NomSociete') === null || window.sessionStorage.getItem('Societe') === null) {\n");
      out.write("//                    window.location.href = \"/workflowDemande-web/index\";\n");
      out.write("//                }\n");
      out.write("//            });\n");
      out.write("        </script>\n");
      out.write("\n");
      out.write("        <script src=\"js/plugin/datatables/jquery.dataTables.min.js\"></script>\n");
      out.write("        <script src=\"js/plugin/datatables/dataTables.colVis.min.js\"></script>\n");
      out.write("        <script src=\"js/plugin/datatables/dataTables.tableTools.min.js\"></script>\n");
      out.write("        <script src=\"js/plugin/datatables/dataTables.bootstrap.min.js\"></script>\n");
      out.write("        <script src=\"js/plugin/datatable-responsive/datatables.responsive.min.js\"></script>  \n");
      out.write("        <script src=\"body_page_js/otherfunction.js\" type=\"text/javascript\"></script>\n");
      out.write("        <script src=\"js/plugin/other-plugin/mymenu.js\"></script>  \n");
      out.write("    </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_spring_005feval_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:eval
    org.springframework.web.servlet.tags.EvalTag _jspx_th_spring_005feval_005f0 = (org.springframework.web.servlet.tags.EvalTag) _005fjspx_005ftagPool_005fspring_005feval_0026_005fvar_005fexpression_005fnobody.get(org.springframework.web.servlet.tags.EvalTag.class);
    boolean _jspx_th_spring_005feval_005f0_reused = false;
    try {
      _jspx_th_spring_005feval_005f0.setPageContext(_jspx_page_context);
      _jspx_th_spring_005feval_005f0.setParent(null);
      // /WEB-INF/master_page/index.jsp(4,0) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005feval_005f0.setVar("url_base");
      // /WEB-INF/master_page/index.jsp(4,0) name = expression type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005feval_005f0.setExpression("@environment.url_base");
      int[] _jspx_push_body_count_spring_005feval_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005feval_005f0 = _jspx_th_spring_005feval_005f0.doStartTag();
        if (_jspx_th_spring_005feval_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005feval_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005feval_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005feval_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005feval_0026_005fvar_005fexpression_005fnobody.reuse(_jspx_th_spring_005feval_005f0);
      _jspx_th_spring_005feval_005f0_reused = true;
    } finally {
      if (!_jspx_th_spring_005feval_005f0_reused) {
        _jspx_th_spring_005feval_005f0.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_spring_005feval_005f0);
      }
    }
    return false;
  }

  private boolean _jspx_meth_spring_005feval_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:eval
    org.springframework.web.servlet.tags.EvalTag _jspx_th_spring_005feval_005f1 = (org.springframework.web.servlet.tags.EvalTag) _005fjspx_005ftagPool_005fspring_005feval_0026_005fvar_005fexpression_005fnobody.get(org.springframework.web.servlet.tags.EvalTag.class);
    boolean _jspx_th_spring_005feval_005f1_reused = false;
    try {
      _jspx_th_spring_005feval_005f1.setPageContext(_jspx_page_context);
      _jspx_th_spring_005feval_005f1.setParent(null);
      // /WEB-INF/master_page/index.jsp(5,0) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005feval_005f1.setVar("idModule");
      // /WEB-INF/master_page/index.jsp(5,0) name = expression type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005feval_005f1.setExpression("@environment.idModule");
      int[] _jspx_push_body_count_spring_005feval_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005feval_005f1 = _jspx_th_spring_005feval_005f1.doStartTag();
        if (_jspx_th_spring_005feval_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005feval_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005feval_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005feval_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005feval_0026_005fvar_005fexpression_005fnobody.reuse(_jspx_th_spring_005feval_005f1);
      _jspx_th_spring_005feval_005f1_reused = true;
    } finally {
      if (!_jspx_th_spring_005feval_005f1_reused) {
        _jspx_th_spring_005feval_005f1.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_spring_005feval_005f1);
      }
    }
    return false;
  }

  private boolean _jspx_meth_spring_005feval_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:eval
    org.springframework.web.servlet.tags.EvalTag _jspx_th_spring_005feval_005f2 = (org.springframework.web.servlet.tags.EvalTag) _005fjspx_005ftagPool_005fspring_005feval_0026_005fvar_005fexpression_005fnobody.get(org.springframework.web.servlet.tags.EvalTag.class);
    boolean _jspx_th_spring_005feval_005f2_reused = false;
    try {
      _jspx_th_spring_005feval_005f2.setPageContext(_jspx_page_context);
      _jspx_th_spring_005feval_005f2.setParent(null);
      // /WEB-INF/master_page/index.jsp(6,0) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005feval_005f2.setVar("url_base_access");
      // /WEB-INF/master_page/index.jsp(6,0) name = expression type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005feval_005f2.setExpression("@environment.url_base_access");
      int[] _jspx_push_body_count_spring_005feval_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005feval_005f2 = _jspx_th_spring_005feval_005f2.doStartTag();
        if (_jspx_th_spring_005feval_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005feval_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005feval_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005feval_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005feval_0026_005fvar_005fexpression_005fnobody.reuse(_jspx_th_spring_005feval_005f2);
      _jspx_th_spring_005feval_005f2_reused = true;
    } finally {
      if (!_jspx_th_spring_005feval_005f2_reused) {
        _jspx_th_spring_005feval_005f2.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_spring_005feval_005f2);
      }
    }
    return false;
  }

  private boolean _jspx_meth_spring_005feval_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:eval
    org.springframework.web.servlet.tags.EvalTag _jspx_th_spring_005feval_005f3 = (org.springframework.web.servlet.tags.EvalTag) _005fjspx_005ftagPool_005fspring_005feval_0026_005fvar_005fexpression_005fnobody.get(org.springframework.web.servlet.tags.EvalTag.class);
    boolean _jspx_th_spring_005feval_005f3_reused = false;
    try {
      _jspx_th_spring_005feval_005f3.setPageContext(_jspx_page_context);
      _jspx_th_spring_005feval_005f3.setParent(null);
      // /WEB-INF/master_page/index.jsp(7,0) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005feval_005f3.setVar("currencyScale");
      // /WEB-INF/master_page/index.jsp(7,0) name = expression type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005feval_005f3.setExpression("@environment.currencyScale");
      int[] _jspx_push_body_count_spring_005feval_005f3 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005feval_005f3 = _jspx_th_spring_005feval_005f3.doStartTag();
        if (_jspx_th_spring_005feval_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005feval_005f3[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005feval_005f3.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005feval_005f3.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005feval_0026_005fvar_005fexpression_005fnobody.reuse(_jspx_th_spring_005feval_005f3);
      _jspx_th_spring_005feval_005f3_reused = true;
    } finally {
      if (!_jspx_th_spring_005feval_005f3_reused) {
        _jspx_th_spring_005feval_005f3.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_spring_005feval_005f3);
      }
    }
    return false;
  }

  private boolean _jspx_meth_spring_005feval_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:eval
    org.springframework.web.servlet.tags.EvalTag _jspx_th_spring_005feval_005f4 = (org.springframework.web.servlet.tags.EvalTag) _005fjspx_005ftagPool_005fspring_005feval_0026_005fvar_005fexpression_005fnobody.get(org.springframework.web.servlet.tags.EvalTag.class);
    boolean _jspx_th_spring_005feval_005f4_reused = false;
    try {
      _jspx_th_spring_005feval_005f4.setPageContext(_jspx_page_context);
      _jspx_th_spring_005feval_005f4.setParent(null);
      // /WEB-INF/master_page/index.jsp(8,0) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005feval_005f4.setVar("url_base_fichier_base");
      // /WEB-INF/master_page/index.jsp(8,0) name = expression type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005feval_005f4.setExpression("@environment.url_base_fichier_base");
      int[] _jspx_push_body_count_spring_005feval_005f4 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005feval_005f4 = _jspx_th_spring_005feval_005f4.doStartTag();
        if (_jspx_th_spring_005feval_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005feval_005f4[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005feval_005f4.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005feval_005f4.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005feval_0026_005fvar_005fexpression_005fnobody.reuse(_jspx_th_spring_005feval_005f4);
      _jspx_th_spring_005feval_005f4_reused = true;
    } finally {
      if (!_jspx_th_spring_005feval_005f4_reused) {
        _jspx_th_spring_005feval_005f4.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_spring_005feval_005f4);
      }
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f0 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f0_reused = false;
    try {
      _jspx_th_c_005fimport_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f0.setParent(null);
      // /WEB-INF/master_page/index.jsp(127,8) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f0.setUrl("/header");
      int[] _jspx_push_body_count_c_005fimport_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f0 = _jspx_th_c_005fimport_005f0.doStartTag();
        if (_jspx_th_c_005fimport_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f0);
      _jspx_th_c_005fimport_005f0_reused = true;
    } finally {
      if (!_jspx_th_c_005fimport_005f0_reused) {
        _jspx_th_c_005fimport_005f0.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_c_005fimport_005f0);
      }
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f0 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    boolean _jspx_th_spring_005fmessage_005f0_reused = false;
    try {
      _jspx_th_spring_005fmessage_005f0.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fmessage_005f0.setParent(null);
      // /WEB-INF/master_page/index.jsp(152,81) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fmessage_005f0.setCode("pharmacie.global.VEUILLEZPATIENTERQUELQUESSECONDES");
      int[] _jspx_push_body_count_spring_005fmessage_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fmessage_005f0 = _jspx_th_spring_005fmessage_005f0.doStartTag();
        if (_jspx_th_spring_005fmessage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fmessage_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fmessage_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fmessage_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f0);
      _jspx_th_spring_005fmessage_005f0_reused = true;
    } finally {
      if (!_jspx_th_spring_005fmessage_005f0_reused) {
        _jspx_th_spring_005fmessage_005f0.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_spring_005fmessage_005f0);
      }
    }
    return false;
  }
}
