/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.11
 * Generated at: 2023-02-07 13:24:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.body_005fpage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.text.DateFormat;

public final class ListePatient_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/Admin/.m2/repository/org/springframework/spring-webmvc/4.3.7.RELEASE/spring-webmvc-4.3.7.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1488353688000L));
    _jspx_dependants.put("file:/C:/Users/Admin/.m2/repository/org/springframework/spring-webmvc/4.3.7.RELEASE/spring-webmvc-4.3.7.RELEASE.jar", Long.valueOf(1666169773704L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("java.text.DateFormat");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005feval_0026_005fvar_005fexpression_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fspring_005feval_0026_005fvar_005fexpression_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fspring_005feval_0026_005fvar_005fexpression_005fnobody.release();
    _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
    String date = dateFormat.format(new Date());

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      if (_jspx_meth_spring_005feval_005f0(_jspx_page_context))
        return;
      out.write('\n');
      if (_jspx_meth_spring_005feval_005f1(_jspx_page_context))
        return;
      out.write('\n');
      if (_jspx_meth_spring_005feval_005f2(_jspx_page_context))
        return;
      out.write('\n');
      if (_jspx_meth_spring_005feval_005f3(_jspx_page_context))
        return;
      out.write('\n');
      if (_jspx_meth_spring_005feval_005f4(_jspx_page_context))
        return;
      out.write('\n');
      if (_jspx_meth_spring_005feval_005f5(_jspx_page_context))
        return;
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "css_declare.jsp", out, false);
      out.write("   \n");
      out.write("        <title>");
      if (_jspx_meth_spring_005fmessage_005f0(_jspx_page_context))
        return;
      out.write("</title>\n");
      out.write("        <style>\n");
      out.write("            .myDropDoxnStyle_L .select2-results .select2-result-label{\n");
      out.write("                padding:0;\n");
      out.write("            }\n");
      out.write("            #sessionExpirationConfirm{\n");
      out.write("                z-index:999999999;\n");
      out.write("            }\n");
      out.write("            .longtd,input{\n");
      out.write("                white-space: nowrap;\n");
      out.write("                overflow: hidden;\n");
      out.write("                text-overflow: ellipsis;\n");
      out.write("                font-size:12px;\n");
      out.write("            }\n");
      out.write("            label{\n");
      out.write("                font-size: 12px;\n");
      out.write("                font-weight: 300;\n");
      out.write("            }\n");
      out.write("            .nav-tabs.bordered {\n");
      out.write("                background: #3276b1;\n");
      out.write("            }\n");
      out.write("            .smart-form fieldset {\n");
      out.write("                padding: 0px 14px 5px;\n");
      out.write("            }\n");
      out.write("            .well{\n");
      out.write("                padding-top: 0;\n");
      out.write("            }\n");
      out.write("            [class^=\"select2\"],select{\n");
      out.write("                font-size: 12px;\n");
      out.write("            }\n");
      out.write("            .form-group {\n");
      out.write("                margin-bottom: 5px;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            legend {\n");
      out.write("                margin: 0px 0 10px;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .input-xs {\n");
      out.write("                height: 25px;\n");
      out.write("                font-size: 12px;\n");
      out.write("            }\n");
      out.write("            .btn-circle {\n");
      out.write("                width: 25px;\n");
      out.write("                height: 25px;\n");
      out.write("                padding: 4px 0px;\n");
      out.write("                font-size: 12px;\n");
      out.write("            }\n");
      out.write("            .smart-form .inline-group .radio {\n");
      out.write("                float: left;\n");
      out.write("                margin-right: 5px;\n");
      out.write("            }\n");
      out.write("            @media screen{\n");
      out.write("                #LabelMotif{\n");
      out.write("                    display: block;\n");
      out.write("                    color: #0A0A0A;\n");
      out.write("                    text-align: left;\n");
      out.write("                    font-size:100%;\n");
      out.write("                }\n");
      out.write("                .rowSelected{\n");
      out.write("                    background-color:rgb(217, 237, 247);\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("            .form-control[disabled], .form-control[readonly], fieldset[disabled] .form-control {\n");
      out.write("                background-color: #fff;\n");
      out.write("            }\n");
      out.write("            .control-label{\n");
      out.write("                top: 5px;\n");
      out.write("            }\n");
      out.write("            .selectionne{\n");
      out.write("                background-color: #BAD2E4;\n");
      out.write("            }\n");
      out.write("            #select2-drop.myDropDoxnStyle_L{\n");
      out.write("                width: 40% !important;\n");
      out.write("            }\n");
      out.write("            .btn-group,  .btn-group-vertical {\n");
      out.write("                position: relative;\n");
      out.write("                display: block;\n");
      out.write("                vertical-align: middle;\n");
      out.write("            }\n");
      out.write("            .champOblig{\n");
      out.write("                color: red;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            select2-choice ,.form-control[disabled], .form-control[readonly], fieldset[disabled] .form-control , [disabled] {\n");
      out.write("                background-color: #fff;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .select2-container {\n");
      out.write("                width:100%;\n");
      out.write("            }\n");
      out.write("            .select2-container a.select2-choice {\n");
      out.write("                font-size: 11px;\n");
      out.write("                height: 25px;\n");
      out.write("                padding: 4px 12px;\n");
      out.write("                line-height: 1.42857;\n");
      out.write("            }\n");
      out.write("            .select2-container .select2-choice .select2-arrow {\n");
      out.write("                padding-top:6px;\n");
      out.write("                width: 25px;\n");
      out.write("            }\n");
      out.write("            .input-group-addon {\n");
      out.write("                padding: 4px 6px;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            td {\n");
      out.write("                vertical-align: middle !important;\n");
      out.write("            }\n");
      out.write("            #tableListPatient >thead > tr th:nth-child(1),\n");
      out.write("            #tableListPatient >tbody > tr td:nth-child(1){\n");
      out.write("                width: 3%!important;\n");
      out.write("            }\n");
      out.write("            #tableListPatient >thead > tr th:nth-child(2),\n");
      out.write("            #tableListPatient >tbody > tr td:nth-child(2){\n");
      out.write("                width: 8%!important;\n");
      out.write("            }\n");
      out.write("            #tableListPatient >thead > tr th:nth-child(3),\n");
      out.write("            #tableListPatient >tbody > tr td:nth-child(3){\n");
      out.write("                width: 8%!important;\n");
      out.write("            }\n");
      out.write("            #tableListPatient >thead > tr th:nth-child(4)\n");
      out.write("            {\n");
      out.write("                width: 8%!important;\n");
      out.write("            }\n");
      out.write("            #tableListPatient >tbody > tr td:nth-child(4){\n");
      out.write("                width: 8%!important;\n");
      out.write("                text-align: right\n");
      out.write("            }\n");
      out.write("            #tableListPatient >thead > tr th:nth-child(5){\n");
      out.write("                width: 12%!important;\n");
      out.write("            }\n");
      out.write("            #tableListPatient >tbody > tr td:nth-child(5){\n");
      out.write("                width: 12%!important;\n");
      out.write("                text-align: right\n");
      out.write("            }\n");
      out.write("            #tableListPatient >thead > tr th:nth-child(6)\n");
      out.write("            {\n");
      out.write("                width: 10%!important;\n");
      out.write("            }\n");
      out.write("            #tableListPatient >tbody > tr td:nth-child(6){\n");
      out.write("                width: 10%!important;\n");
      out.write("                text-align: right\n");
      out.write("            }\n");
      out.write("            #tableListPatient >thead > tr th:nth-child(7)\n");
      out.write("            {\n");
      out.write("                width: 10%!important;\n");
      out.write("            }\n");
      out.write("            #tableListPatient >tbody > tr td:nth-child(7){\n");
      out.write("                width: 10%!important;\n");
      out.write("                text-align: right\n");
      out.write("            }\n");
      out.write("            #tableListPatient >thead > tr th:nth-child(8),\n");
      out.write("            #tableListPatient >tbody > tr td:nth-child(8){\n");
      out.write("                width: 22%!important;\n");
      out.write("            }\n");
      out.write("            #tableListPatient >thead > tr th:nth-child(9),\n");
      out.write("            #tableListPatient >tbody > tr td:nth-child(9){\n");
      out.write("                width: 8%!important;\n");
      out.write("            }\n");
      out.write("            #tableListPatient >thead > tr th:nth-child(10),\n");
      out.write("            #tableListPatient >tbody > tr td:nth-child(10){\n");
      out.write("                width: 5%!important;\n");
      out.write("            }\n");
      out.write("            #tableListPatient >thead > tr th:nth-child(11),\n");
      out.write("            #tableListPatient >tbody > tr td:nth-child(11){\n");
      out.write("                width: 8%!important;\n");
      out.write("            }\n");
      out.write("            #tableListPatient >thead > tr th:nth-child(12),\n");
      out.write("            #tableListPatient >tbody > tr td:nth-child(12){\n");
      out.write("                width: 5%!important;\n");
      out.write("            }\n");
      out.write("            #tableListPatient  >tbody {\n");
      out.write("                flex: 1 1 auto;\n");
      out.write("                width: 100%;\n");
      out.write("                display: block;\n");
      out.write("                overflow-y: scroll;\n");
      out.write("                overflow-x: hidden;\n");
      out.write("                min-height: 20px;\n");
      out.write("                max-height: calc(100vh - 245px);\n");
      out.write("                height:auto !important;\n");
      out.write("            }\n");
      out.write("            #tableListPatient {\n");
      out.write("                display: flex;\n");
      out.write("                flex-flow: column;\n");
      out.write("                height: 100%;\n");
      out.write("                width: 100%;\n");
      out.write("            }\n");
      out.write("            #tableListPatient >thead, #tableListPatient >tbody tr {\n");
      out.write("                display: table;\n");
      out.write("                table-layout: fixed;\n");
      out.write("            }\n");
      out.write("            #tableListPatient >thead {\n");
      out.write("                /* head takes the height it requires, \n");
      out.write("                and it's not scaled when table is resized */\n");
      out.write("                width: calc(100% - 0.4em ) !important;\n");
      out.write("                flex: 0 0 auto;\n");
      out.write("            }\n");
      out.write("            #tableListPatient >tbody tr {\n");
      out.write("                width: 100%;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            #tableListPatient > tbody > tr > td,\n");
      out.write("            #tableListPatient > tbody > tr > th,\n");
      out.write("            #tableListPatient > tfoot > tr > td,\n");
      out.write("            #tableListPatient > tfoot > tr > th,\n");
      out.write("            #tableListPatient > thead > tr > td,\n");
      out.write("            #tableListPatient > thead > tr > th {\n");
      out.write("                padding: 3px 5px!important;\n");
      out.write("                font-size: 12px;\n");
      out.write("            }\n");
      out.write("            .btn.filtreActif{\n");
      out.write("                background-color: white;\n");
      out.write("                color: black;\n");
      out.write("                border-left-width: 5px;\n");
      out.write("                border-bottom-color: #0000003b;\n");
      out.write("                border-top-color: #0000003b;\n");
      out.write("                border-right-color: #0000003b;\n");
      out.write("                margin: 0px 2px!important;\n");
      out.write("                border-radius: 1px;\n");
      out.write("                box-sizing: border-box;\n");
      out.write("                width: calc(33.33% - 19px);\n");
      out.write("            }\n");
      out.write("            .btn.etatCli{\n");
      out.write("                background-color: white;\n");
      out.write("                color: black;\n");
      out.write("                border-left-width: 5px;\n");
      out.write("                border-bottom-color: #0000003b!important;\n");
      out.write("                border-top-color: #0000003b!important;\n");
      out.write("                border-right-color: #0000003b!important;\n");
      out.write("                margin: 0px 2px!important;\n");
      out.write("                border-radius: 1px;\n");
      out.write("                box-sizing: border-box;\n");
      out.write("                width: calc(17.73% - 19px);\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .widget-body{\n");
      out.write("                z-index: 0;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            #date_du{\n");
      out.write("                z-index: 0 !important;\n");
      out.write("            }\n");
      out.write("            #date_au{\n");
      out.write("                z-index: 0 !important;\n");
      out.write("            }\n");
      out.write("            #dateNaissRecherchePatient{\n");
      out.write("                z-index: 0 !important;\n");
      out.write("            }\n");
      out.write("        </style>\n");
      out.write("    </head>\n");
      out.write("    <body class=\"styleCsys\" > \n");
      out.write("        <section id=\"widget-grid\" >\n");
      out.write("\n");
      out.write("            <!-- row -->\n");
      out.write("            <div class=\"row hidden-print screen\">\n");
      out.write("                <article class=\"col-xs-12 col-sm-12 col-md-12 col-lg-12\" style=\"padding-right: 2px;\">\n");
      out.write("                    <div class=\"jarviswidget jarviswidget-color-redLight\"  data-widget-editbutton=\"false\" data-widget-deletebutton=\"false\">\n");
      out.write("\n");
      out.write("                        <header class='screen' >\n");
      out.write("                            <a class=\"btn btn-default  pull-left\" id=\"rafresh\" > \n");
      out.write("                                <span class=\"widget-icon\"><i class=\"glyphicon glyphicon-refresh\"></i></span>  \n");
      out.write("                            </a>\n");
      out.write("                            <h2><strong id=\"etat-header\" >Gestion des patients </strong></h2>\n");
      out.write("                            <div style=\"float: right;\">\n");
      out.write("                                <a class=\"btn btn-default accessCtrl pull-right\" id=\"btnFermer\"> \n");
      out.write("                                    <span class=\"widget-icon\"><i class=\"glyphicon btn-danger glyphicon-log-out\"></i> ");
      if (_jspx_meth_spring_005fmessage_005f1(_jspx_page_context))
        return;
      out.write("</span>\n");
      out.write("                                </a>\n");
      out.write("                                <a class=\"btn btn-default accessCtrl pull-right\" id=\"btn_Exporter\"> \n");
      out.write("                                    <span class=\"widget-icon\"><i class=\"fa fa-list\"></i>Excel</span>\n");
      out.write("                                </a>\n");
      out.write("                                <div id='bntContainer'style=\"float: right;width:135%\"></div></div>\n");
      out.write("                        </header>\n");
      out.write("                        <!-- widget div-->\n");
      out.write("                        <div style=\"min-height: calc(100vh - 55px);\">\n");
      out.write("                            <div class=\"widget-body screen col-md-12\">\n");
      out.write("                                <div class=\"row\" >\n");
      out.write("                                    <div class=\"col-md-6 form-group\" style=\"float: right;\">\n");
      out.write("\n");
      out.write("                                        <label class=\"btn btn-default active etatCli\" name=\"btnTousActif\" style=\"border-color:#1ac165; font-size:12px;\">\n");
      out.write("                                            <i class=\"fa fa-check-circle\" style=\"/*font-size: 1.5em;*/\"></i>\n");
      out.write("                                            <span>Hospitalisé</span>\n");
      out.write("                                        </label>\n");
      out.write("                                        <label class=\"btn etatCli\" name=\"btnTousActif\" style=\"border-color:#2149df;font-size:12px;\">\n");
      out.write("                                            <i class=\"fa fa-search\" style=\"/*font-size: 1.5em;*/\"></i>\n");
      out.write("                                            <span>Autorisé</span>\n");
      out.write("                                        </label>\n");
      out.write("                                        <label class=\"btn etatCli\" name=\"btnTousActif\" style=\"border-color: #ec8e8e;font-size:12px; padding: 7px 0px 5px 0px;\">\n");
      out.write("                                            <i class=\"fa fa-search\" style=\"/*font-size: 1.5em;*/\"></i>\n");
      out.write("                                            <span>Audité</span>\n");
      out.write("                                        </label>\n");
      out.write("                                        <label class=\"btn etatCli\" name=\"btnTousActif\" style=\"border-color:#de0f0f; font-size:12px;\">\n");
      out.write("                                            <i class=\"fa fa-search\" style=\"/*font-size: 1.5em;*/\"></i>\n");
      out.write("                                            <span>Facturé</span>\n");
      out.write("                                        </label>\n");
      out.write("                                        <label class=\"btn etatCli\" name=\"btnTousActif\" style=\"border-color: #efbb50;font-size:12px;\">\n");
      out.write("                                            <i class=\"fa fa-search\" style=\"/*font-size: 1.5em;*/\"></i>\n");
      out.write("                                            <span>en Instance</span>\n");
      out.write("                                        </label>\n");
      out.write("                                        <label class=\"btn etatCli\" name=\"btnTousActif\" style=\"border-color: #5e6561;font-size:12px;padding: 7px 0px 5px 0px;\">\n");
      out.write("                                            <i class=\"fa fa-search\" style=\"/*font-size: 1.5em;*/\"></i>\n");
      out.write("                                            <span>Tous</span>\n");
      out.write("                                        </label>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"col-md-4\" style=\"float: right;\">\n");
      out.write("                                        <div class=\"form-group col-md-4\">\n");
      out.write("                                            <label class=\"col-md-2 control-label\">Du </label>\n");
      out.write("                                            <div class=\"col-md-8 input-group\" id=\"_date_debut_Parent\">\n");
      out.write("                                                <input id=\"date_du\" type=\"text\" name=\"datedebut\" placeholder=\"Date Début\" class=\"form-control datepicker input-xs\" data-mask=\"00/00/0000\" data-mask-clearifnotmatch=\"true\">\n");
      out.write("                                                <span class=\"input-group-addon\"><i class=\"fa fa-calendar\"></i></span>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"col-md-4 form-group\" >\n");
      out.write("                                            <label class=\"col-md-2 control-label\">Au </label>\n");
      out.write("\n");
      out.write("                                            <div id=\"_date_fin_Parent\" class=\"input-group  col-md-8\" >\n");
      out.write("                                                <input  id=\"date_au\" type=\"text\" name=\"datefin\" placeholder=\"Date Fin\" class=\"form-control datepicker input-xs\" data-mask=\"00/00/0000\" data-mask-clearifnotmatch=\"true\">\n");
      out.write("                                                <span class=\"input-group-addon\"><i class=\"fa fa-calendar\"></i></span>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"col-md-4  form-group \">\n");
      out.write("                                            <button id=\"btnact\" class=\"btn btn-outline-primary\" type=\"button\"><span><i\n");
      out.write("                                                        class=\"fal fa-search mr-1\"></i>\n");
      out.write("                                                </span></button>\n");
      out.write("                                            <button id=\"init_btn\" class=\"btn btn-outline-dark\" type=\"button\"><span><i\n");
      out.write("                                                        class=\"fal fa-sync-alt mr-1\"></i></span></button>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"col-md-1\">\n");
      out.write("                                        <a class=\"btn  collapsed waves-effect waves-themed\" data-toggle=\"collapse\"\n");
      out.write("                                           href=\"#collapseExample\" role=\"button\" aria-expanded=\"false\"\n");
      out.write("                                           aria-controls=\"collapseExample\" title=\"Recherche avancée\">\n");
      out.write("                                            <span><i class=\"fal fa-search-plus mr-1 fa-2x\"></i></span>\n");
      out.write("                                        </a>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"collapse row col-md-12 form-group\" id=\"collapseExample\">\n");
      out.write("                                        <label class=\"input\">\n");
      out.write("                                            <div class=\"icon-addon addon-md\">\n");
      out.write("                                                <input class=\"form-control\" id=\"Identifiant\" type=\"text\"\n");
      out.write("                                                       placeholder=\"Identifiant\">\n");
      out.write("                                                <label class=\"glyphicon glyphicon-search\" rel=\"tooltip\" title=\"\" style=\"padding: 10px 0;\"></label>\n");
      out.write("                                            </div>\n");
      out.write("                                        </label>\n");
      out.write("                                        <label class=\"input\">\n");
      out.write("                                            <div class=\"icon-addon addon-md\">\n");
      out.write("                                                <input class=\"form-control\" id=\"cin\" type=\"text\"\n");
      out.write("                                                       placeholder=\"N°Pièce d'identité\">\n");
      out.write("                                                <label class=\"glyphicon glyphicon-search\" rel=\"tooltip\" title=\"\" style=\"padding: 10px 0;\"></label>\n");
      out.write("                                            </div>\n");
      out.write("                                        </label><!-- comment -->\n");
      out.write("                                        <label class=\"input\">\n");
      out.write("                                            <div class=\"icon-addon addon-md\">\n");
      out.write("                                                <input class=\"form-control\" id=\"numfac\" type=\"text\"\n");
      out.write("                                                       placeholder=\"N°Facture\">\n");
      out.write("                                                <label class=\"glyphicon glyphicon-search\" rel=\"tooltip\" title=\"\" style=\"padding: 10px 0;\"></label>\n");
      out.write("                                            </div>\n");
      out.write("                                        </label>\n");
      out.write("                                        <label class=\"input\">\n");
      out.write("                                            <div class=\"icon-addon addon-md\">\n");
      out.write("                                                <input class=\"form-control\" id=\"NumCha\" type=\"text\"\n");
      out.write("                                                       placeholder=\"N°Chambre\">\n");
      out.write("                                                <label class=\"glyphicon glyphicon-search\" rel=\"tooltip\" title=\"\" style=\"padding: 10px 0;\"></label>\n");
      out.write("                                            </div>\n");
      out.write("                                        </label>\n");
      out.write("\n");
      out.write("                                        <label class=\"input\">\n");
      out.write("                                            <div class=\"icon-addon addon-md\">\n");
      out.write("                                                <input class=\"form-control\" id=\"numDoss\" type=\"text\"\n");
      out.write("                                                       placeholder=\"Numéro dossier\">\n");
      out.write("                                                <label class=\"glyphicon glyphicon-search\" rel=\"tooltip\" title=\"\" style=\"padding: 10px 0;\"></label>\n");
      out.write("                                            </div>\n");
      out.write("                                        </label>\n");
      out.write("                                        <label class=\"input\">\n");
      out.write("                                            <div class=\"icon-addon addon-md\">\n");
      out.write("                                                <input class=\"form-control\" id=\"prenom\" type=\"text\"\n");
      out.write("                                                       placeholder=\"Prénom\">\n");
      out.write("                                                <label class=\"glyphicon glyphicon-search\" rel=\"tooltip\" title=\"\" style=\"padding: 10px 0;\"></label>\n");
      out.write("                                            </div>\n");
      out.write("                                        </label>\n");
      out.write("                                        <label class=\"input\">\n");
      out.write("                                            <div class=\"icon-addon addon-md\">\n");
      out.write("                                                <input class=\"form-control\" id=\"Nom\" type=\"text\"\n");
      out.write("                                                       placeholder=\"Nom\">\n");
      out.write("                                                <label class=\"glyphicon glyphicon-search\" rel=\"tooltip\" title=\"\" style=\"padding: 10px 0;\"></label>\n");
      out.write("                                            </div>\n");
      out.write("                                        </label>\n");
      out.write("                                        <div class=\"col-md-4  form-group \">\n");
      out.write("                                            <div class=\"col-md-4\">\n");
      out.write("                                                <div class=\"input-group\"> \n");
      out.write("                                                    <input id=\"dateNaissRecherchePatient\" type=\"text\"\n");
      out.write("                                                           class=\"form-control _date_deb_fin_filtre\" data-mask=\"00/00/0000\"\n");
      out.write("                                                           placeholder=\"Date de naissance\">\n");
      out.write("                                                    <span class=\"input-group-addon\"><i class=\"fa fa-calendar\"></i></span>\n");
      out.write("                                                </div>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>  \n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"row\">\n");
      out.write("                                    <div  id=\"_grid_ListPatient\">\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                </article>\n");
      out.write("            </div>\n");
      out.write("        </section>   \n");
      out.write("\n");
      out.write("        <div class=\"modal fade \" id=\"parametrage\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\n");
      out.write("            <div class=\"modal-dialog centre_screen\" style=\"width: 850px;\">\n");
      out.write("                <div class=\"modal-content\">\n");
      out.write("                    <div class=\"modal-header\"   style=\"color: #1293b8;\">\n");
      out.write("                        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\"><i class=\"fa fa-times\"></i></button>\n");
      out.write("                        <h4  class=\"modal-title\"><i style=\"font-size: 20px;\" class=\"glyphicon glyphicon-log-out\"></i> <span>Paramétrage impression</span></h4>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div id=\"parametragebody\" class=\"modal-body\"  style=\"overflow-x: hidden;overflow-y: auto;max-height: 200px;\">\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div class=\"modal-footer\" >\n");
      out.write("\n");
      out.write("                        <button id=\"btnCloseModalImpr\" type=\"\" onClick=\"$('#parametrage').modal('hide');\" class=\"btn btn-default btnCloseImprCh\" style=\"float:right\"><i class=\"fa fa-times\"></i> Fermer</button>\n");
      out.write("                        <div onclick=\"validerparametrage()\" >\n");
      out.write("                            <a href=\"javascript:void(0);\" class=\"btn btn-default\"   style=\"margin-right:10px;float:right\"> \n");
      out.write("                                <span class=\"widget-icon\"><i class=\"fa fa-check\"></i></span>&nbsp;&nbsp;Valider\n");
      out.write("                            </a>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>           \n");
      out.write("\n");
      out.write("        <div class=\"modal fade \" id=\"sessionExpirationConfirm\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\n");
      out.write("            <div class=\"modal-dialog centre_screen\" style=\"width: 530px;\">\n");
      out.write("                <div class=\"modal-content\">\n");
      out.write("                    <div class=\"modal-header bg-color-redLight txt-color-white\"   >\n");
      out.write("                        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\"><i class=\"fa fa-times\"></i></button>\n");
      out.write("                        <h4  class=\"modal-title\"><i style=\"font-size: 20px;\" class=\"glyphicon glyphicon-log-out\"></i> <label>Expiration de session</label></h4>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div id=\"popup_sessionExpiration\" class=\"modal-body\">\n");
      out.write("                        <label>Votre session a expiré! Pour des raisons de sécurité, vous serez automatiquement déconnecté après <span id=\"SecondsUntilExpire\"></span> secondes</label>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <div  class=\"modal-footer\" style=\"padding: 1px 20px 4px;\">\n");
      out.write("                        <div class=\"row\"><br>\n");
      out.write("                            <div style=\"padding: 1px 20px 4px;\" align=\"right\">\n");
      out.write("                                <button id=\"submitSessionExpiration\" type=\"button\" class=\"btn btn-success\"><i class=\"fa fa-sign-in\"></i>&nbsp; Rester connecté</button>\n");
      out.write("                                <button id=\"cancelSessionExpiration\" type=\"button\" class=\"btn btn-danger\" ><i class=\"fa fa-sign-out\"></i>&nbsp; Se déconnecter</button>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div> \n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div> \n");
      out.write("\n");
      out.write("        <style>\n");
      out.write("            [id^=\"drag\"]{\n");
      out.write("                width: 6%;\n");
      out.write("                height: 40px;\n");
      out.write("                margin: 0.5%;\n");
      out.write("                display: inline-block;\n");
      out.write("                color: white;\n");
      out.write("                border-radius: 0.75em;\n");
      out.write("                padding: 1.3%;\n");
      out.write("                font-weight: bolder;\n");
      out.write("                -webkit-transform: translate(0px, 0px);\n");
      out.write("                transform: translate(0px, 0px);\n");
      out.write("            }\n");
      out.write("            ul.tabs-left{\n");
      out.write("                overflow-y: scroll;\n");
      out.write("                max-height: 450px;\n");
      out.write("                overflow-x: hidden;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            #drag-me::before {\n");
      out.write("                content: \"#\" attr(id);\n");
      out.write("                font-weight: bold;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .select2-container .select2-choice>.select2-chosen{\n");
      out.write("                color: black;\n");
      out.write("            }\n");
      out.write("        </style>\n");
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "EditionModal.jsp", out, false);
      out.write("      \n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "js_declare.jsp", out, false);
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "EditionSessionExpire.jsp", out, false);
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "remise_facture.jsp", out, false);
      out.write("   \n");
      out.write("        <script>\n");
      out.write("            var url_base = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url_base}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\n");
      out.write("            var idModule = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${idModule}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\n");
      out.write("            var url_base_access = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url_base_access}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\n");
      out.write("            var currencyScale = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${currencyScale}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\n");
      out.write("            var url_base_fichier_base = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url_base_fichier_base}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\n");
      out.write("            var numRecept = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${numRecept}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\n");
      out.write("        </script>        \n");
      out.write("        <script src=\"js/backbone_backgrid/underscore-min.js\"></script>        \n");
      out.write("        <script src=\"body_page_js/otherfunction.js?version=");
      out.print(date);
      out.write("\"></script>\n");
      out.write("        <script src=\"body_page_js/BackGridEditor.js?version=");
      out.print(date);
      out.write("\"></script> \n");
      out.write("        <script src=\"body_page_js/ListePatient.js\"></script>\n");
      out.write("        <script src=\"body_page_js/ListePatient_function.js\"></script>\n");
      out.write("        <script src=\"js/plugin/other-plugin/summernote.min.js\"></script> \n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_spring_005feval_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:eval
    org.springframework.web.servlet.tags.EvalTag _jspx_th_spring_005feval_005f0 = (org.springframework.web.servlet.tags.EvalTag) _005fjspx_005ftagPool_005fspring_005feval_0026_005fvar_005fexpression_005fnobody.get(org.springframework.web.servlet.tags.EvalTag.class);
    boolean _jspx_th_spring_005feval_005f0_reused = false;
    try {
      _jspx_th_spring_005feval_005f0.setPageContext(_jspx_page_context);
      _jspx_th_spring_005feval_005f0.setParent(null);
      // /WEB-INF/body_page/ListePatient.jsp(12,0) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005feval_005f0.setVar("url_base");
      // /WEB-INF/body_page/ListePatient.jsp(12,0) name = expression type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005feval_005f0.setExpression("@environment.url_base");
      int[] _jspx_push_body_count_spring_005feval_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005feval_005f0 = _jspx_th_spring_005feval_005f0.doStartTag();
        if (_jspx_th_spring_005feval_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005feval_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005feval_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005feval_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005feval_0026_005fvar_005fexpression_005fnobody.reuse(_jspx_th_spring_005feval_005f0);
      _jspx_th_spring_005feval_005f0_reused = true;
    } finally {
      if (!_jspx_th_spring_005feval_005f0_reused) {
        _jspx_th_spring_005feval_005f0.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_spring_005feval_005f0);
      }
    }
    return false;
  }

  private boolean _jspx_meth_spring_005feval_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:eval
    org.springframework.web.servlet.tags.EvalTag _jspx_th_spring_005feval_005f1 = (org.springframework.web.servlet.tags.EvalTag) _005fjspx_005ftagPool_005fspring_005feval_0026_005fvar_005fexpression_005fnobody.get(org.springframework.web.servlet.tags.EvalTag.class);
    boolean _jspx_th_spring_005feval_005f1_reused = false;
    try {
      _jspx_th_spring_005feval_005f1.setPageContext(_jspx_page_context);
      _jspx_th_spring_005feval_005f1.setParent(null);
      // /WEB-INF/body_page/ListePatient.jsp(13,0) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005feval_005f1.setVar("idModule");
      // /WEB-INF/body_page/ListePatient.jsp(13,0) name = expression type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005feval_005f1.setExpression("@environment.idModule");
      int[] _jspx_push_body_count_spring_005feval_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005feval_005f1 = _jspx_th_spring_005feval_005f1.doStartTag();
        if (_jspx_th_spring_005feval_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005feval_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005feval_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005feval_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005feval_0026_005fvar_005fexpression_005fnobody.reuse(_jspx_th_spring_005feval_005f1);
      _jspx_th_spring_005feval_005f1_reused = true;
    } finally {
      if (!_jspx_th_spring_005feval_005f1_reused) {
        _jspx_th_spring_005feval_005f1.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_spring_005feval_005f1);
      }
    }
    return false;
  }

  private boolean _jspx_meth_spring_005feval_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:eval
    org.springframework.web.servlet.tags.EvalTag _jspx_th_spring_005feval_005f2 = (org.springframework.web.servlet.tags.EvalTag) _005fjspx_005ftagPool_005fspring_005feval_0026_005fvar_005fexpression_005fnobody.get(org.springframework.web.servlet.tags.EvalTag.class);
    boolean _jspx_th_spring_005feval_005f2_reused = false;
    try {
      _jspx_th_spring_005feval_005f2.setPageContext(_jspx_page_context);
      _jspx_th_spring_005feval_005f2.setParent(null);
      // /WEB-INF/body_page/ListePatient.jsp(14,0) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005feval_005f2.setVar("url_base_access");
      // /WEB-INF/body_page/ListePatient.jsp(14,0) name = expression type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005feval_005f2.setExpression("@environment.url_base_access");
      int[] _jspx_push_body_count_spring_005feval_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005feval_005f2 = _jspx_th_spring_005feval_005f2.doStartTag();
        if (_jspx_th_spring_005feval_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005feval_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005feval_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005feval_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005feval_0026_005fvar_005fexpression_005fnobody.reuse(_jspx_th_spring_005feval_005f2);
      _jspx_th_spring_005feval_005f2_reused = true;
    } finally {
      if (!_jspx_th_spring_005feval_005f2_reused) {
        _jspx_th_spring_005feval_005f2.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_spring_005feval_005f2);
      }
    }
    return false;
  }

  private boolean _jspx_meth_spring_005feval_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:eval
    org.springframework.web.servlet.tags.EvalTag _jspx_th_spring_005feval_005f3 = (org.springframework.web.servlet.tags.EvalTag) _005fjspx_005ftagPool_005fspring_005feval_0026_005fvar_005fexpression_005fnobody.get(org.springframework.web.servlet.tags.EvalTag.class);
    boolean _jspx_th_spring_005feval_005f3_reused = false;
    try {
      _jspx_th_spring_005feval_005f3.setPageContext(_jspx_page_context);
      _jspx_th_spring_005feval_005f3.setParent(null);
      // /WEB-INF/body_page/ListePatient.jsp(15,0) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005feval_005f3.setVar("currencyScale");
      // /WEB-INF/body_page/ListePatient.jsp(15,0) name = expression type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005feval_005f3.setExpression("@environment.currencyScale");
      int[] _jspx_push_body_count_spring_005feval_005f3 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005feval_005f3 = _jspx_th_spring_005feval_005f3.doStartTag();
        if (_jspx_th_spring_005feval_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005feval_005f3[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005feval_005f3.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005feval_005f3.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005feval_0026_005fvar_005fexpression_005fnobody.reuse(_jspx_th_spring_005feval_005f3);
      _jspx_th_spring_005feval_005f3_reused = true;
    } finally {
      if (!_jspx_th_spring_005feval_005f3_reused) {
        _jspx_th_spring_005feval_005f3.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_spring_005feval_005f3);
      }
    }
    return false;
  }

  private boolean _jspx_meth_spring_005feval_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:eval
    org.springframework.web.servlet.tags.EvalTag _jspx_th_spring_005feval_005f4 = (org.springframework.web.servlet.tags.EvalTag) _005fjspx_005ftagPool_005fspring_005feval_0026_005fvar_005fexpression_005fnobody.get(org.springframework.web.servlet.tags.EvalTag.class);
    boolean _jspx_th_spring_005feval_005f4_reused = false;
    try {
      _jspx_th_spring_005feval_005f4.setPageContext(_jspx_page_context);
      _jspx_th_spring_005feval_005f4.setParent(null);
      // /WEB-INF/body_page/ListePatient.jsp(16,0) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005feval_005f4.setVar("url_base_fichier_base");
      // /WEB-INF/body_page/ListePatient.jsp(16,0) name = expression type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005feval_005f4.setExpression("@environment.url_base_fichier_base");
      int[] _jspx_push_body_count_spring_005feval_005f4 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005feval_005f4 = _jspx_th_spring_005feval_005f4.doStartTag();
        if (_jspx_th_spring_005feval_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005feval_005f4[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005feval_005f4.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005feval_005f4.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005feval_0026_005fvar_005fexpression_005fnobody.reuse(_jspx_th_spring_005feval_005f4);
      _jspx_th_spring_005feval_005f4_reused = true;
    } finally {
      if (!_jspx_th_spring_005feval_005f4_reused) {
        _jspx_th_spring_005feval_005f4.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_spring_005feval_005f4);
      }
    }
    return false;
  }

  private boolean _jspx_meth_spring_005feval_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:eval
    org.springframework.web.servlet.tags.EvalTag _jspx_th_spring_005feval_005f5 = (org.springframework.web.servlet.tags.EvalTag) _005fjspx_005ftagPool_005fspring_005feval_0026_005fvar_005fexpression_005fnobody.get(org.springframework.web.servlet.tags.EvalTag.class);
    boolean _jspx_th_spring_005feval_005f5_reused = false;
    try {
      _jspx_th_spring_005feval_005f5.setPageContext(_jspx_page_context);
      _jspx_th_spring_005feval_005f5.setParent(null);
      // /WEB-INF/body_page/ListePatient.jsp(17,0) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005feval_005f5.setVar("numRecept");
      // /WEB-INF/body_page/ListePatient.jsp(17,0) name = expression type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005feval_005f5.setExpression("@environment.numRecept");
      int[] _jspx_push_body_count_spring_005feval_005f5 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005feval_005f5 = _jspx_th_spring_005feval_005f5.doStartTag();
        if (_jspx_th_spring_005feval_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005feval_005f5[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005feval_005f5.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005feval_005f5.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005feval_0026_005fvar_005fexpression_005fnobody.reuse(_jspx_th_spring_005feval_005f5);
      _jspx_th_spring_005feval_005f5_reused = true;
    } finally {
      if (!_jspx_th_spring_005feval_005f5_reused) {
        _jspx_th_spring_005feval_005f5.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_spring_005feval_005f5);
      }
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f0 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    boolean _jspx_th_spring_005fmessage_005f0_reused = false;
    try {
      _jspx_th_spring_005fmessage_005f0.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fmessage_005f0.setParent(null);
      // /WEB-INF/body_page/ListePatient.jsp(23,15) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fmessage_005f0.setCode("fb.Acceuil.Patient");
      int[] _jspx_push_body_count_spring_005fmessage_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fmessage_005f0 = _jspx_th_spring_005fmessage_005f0.doStartTag();
        if (_jspx_th_spring_005fmessage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fmessage_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fmessage_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fmessage_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f0);
      _jspx_th_spring_005fmessage_005f0_reused = true;
    } finally {
      if (!_jspx_th_spring_005fmessage_005f0_reused) {
        _jspx_th_spring_005fmessage_005f0.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_spring_005fmessage_005f0);
      }
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f1 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    boolean _jspx_th_spring_005fmessage_005f1_reused = false;
    try {
      _jspx_th_spring_005fmessage_005f1.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fmessage_005f1.setParent(null);
      // /WEB-INF/body_page/ListePatient.jsp(288,117) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fmessage_005f1.setCode("fb.global.fermer");
      int[] _jspx_push_body_count_spring_005fmessage_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fmessage_005f1 = _jspx_th_spring_005fmessage_005f1.doStartTag();
        if (_jspx_th_spring_005fmessage_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fmessage_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fmessage_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fmessage_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f1);
      _jspx_th_spring_005fmessage_005f1_reused = true;
    } finally {
      if (!_jspx_th_spring_005fmessage_005f1_reused) {
        _jspx_th_spring_005fmessage_005f1.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_spring_005fmessage_005f1);
      }
    }
    return false;
  }
}
