/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.11
 * Generated at: 2023-02-08 08:15:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.body_005fpage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.text.DateFormat;

public final class remise_005ffacture_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/Admin/.m2/repository/org/springframework/spring-webmvc/4.3.7.RELEASE/spring-webmvc-4.3.7.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1488353688000L));
    _jspx_dependants.put("file:/C:/Users/Admin/.m2/repository/org/springframework/spring-webmvc/4.3.7.RELEASE/spring-webmvc-4.3.7.RELEASE.jar", Long.valueOf(1666169773704L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("java.text.DateFormat");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005feval_0026_005fvar_005fexpression_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fspring_005feval_0026_005fvar_005fexpression_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fspring_005feval_0026_005fvar_005fexpression_005fnobody.release();
    _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
    String date = dateFormat.format(new Date());

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      if (_jspx_meth_spring_005feval_005f0(_jspx_page_context))
        return;
      out.write('\n');
      if (_jspx_meth_spring_005feval_005f1(_jspx_page_context))
        return;
      out.write('\n');
      if (_jspx_meth_spring_005feval_005f2(_jspx_page_context))
        return;
      out.write('\n');
      if (_jspx_meth_spring_005feval_005f3(_jspx_page_context))
        return;
      out.write('\n');
      if (_jspx_meth_spring_005feval_005f4(_jspx_page_context))
        return;
      out.write('\n');
      if (_jspx_meth_spring_005feval_005f5(_jspx_page_context))
        return;
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "css_declare.jsp", out, false);
      out.write("   \n");
      out.write("        <title>");
      if (_jspx_meth_spring_005fmessage_005f0(_jspx_page_context))
        return;
      out.write("</title>\n");
      out.write("        <style>\n");
      out.write("            .myDropDoxnStyle_L .select2-results .select2-result-label{\n");
      out.write("                padding:0;\n");
      out.write("            }\n");
      out.write("            #sessionExpirationConfirm{\n");
      out.write("                z-index:999999999;\n");
      out.write("            }\n");
      out.write("            .longtd,input{\n");
      out.write("                white-space: nowrap;\n");
      out.write("                overflow: hidden;\n");
      out.write("                text-overflow: ellipsis;\n");
      out.write("                font-size:12px;\n");
      out.write("            }\n");
      out.write("            label{\n");
      out.write("                font-size: 12px;\n");
      out.write("                font-weight: 300;\n");
      out.write("            }\n");
      out.write("            .nav-tabs.bordered {\n");
      out.write("                background: #3276b1;\n");
      out.write("            }\n");
      out.write("            .smart-form fieldset {\n");
      out.write("                padding: 0px 14px 5px;\n");
      out.write("            }\n");
      out.write("            .well{\n");
      out.write("                padding-top: 0;\n");
      out.write("            }\n");
      out.write("            [class^=\"select2\"],select{\n");
      out.write("                font-size: 12px;\n");
      out.write("            }\n");
      out.write("            .form-group {\n");
      out.write("                margin-bottom: 5px;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            legend {\n");
      out.write("                margin: 0px 0 10px;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .input-xs {\n");
      out.write("                height: 25px;\n");
      out.write("                font-size: 12px;\n");
      out.write("            }\n");
      out.write("            .btn-circle {\n");
      out.write("                width: 25px;\n");
      out.write("                height: 25px;\n");
      out.write("                padding: 4px 0px;\n");
      out.write("                font-size: 12px;\n");
      out.write("            }\n");
      out.write("            .smart-form .inline-group .radio {\n");
      out.write("                float: left;\n");
      out.write("                margin-right: 5px;\n");
      out.write("            }\n");
      out.write("            @media screen{\n");
      out.write("                #LabelMotif{\n");
      out.write("                    display: block;\n");
      out.write("                    color: #0A0A0A;\n");
      out.write("                    text-align: left;\n");
      out.write("                    font-size:100%;\n");
      out.write("                }\n");
      out.write("                .rowSelected{\n");
      out.write("                    background-color:rgb(217, 237, 247);\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("            .form-control[disabled], .form-control[readonly], fieldset[disabled] .form-control {\n");
      out.write("                background-color: #fff;\n");
      out.write("            }\n");
      out.write("            .control-label{\n");
      out.write("                top: 5px;\n");
      out.write("            }\n");
      out.write("            .selectionne{\n");
      out.write("                background-color: #BAD2E4;\n");
      out.write("            }\n");
      out.write("            #select2-drop.myDropDoxnStyle_L{\n");
      out.write("                width: 40% !important;\n");
      out.write("            }\n");
      out.write("            .btn-group,  .btn-group-vertical {\n");
      out.write("                position: relative;\n");
      out.write("                display: block;\n");
      out.write("                vertical-align: middle;\n");
      out.write("            }\n");
      out.write("            .champOblig{\n");
      out.write("                color: red;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            select2-choice ,.form-control[disabled], .form-control[readonly], fieldset[disabled] .form-control , [disabled] {\n");
      out.write("                background-color: #fff;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .select2-container {\n");
      out.write("                width:100%;\n");
      out.write("            }\n");
      out.write("            .select2-container a.select2-choice {\n");
      out.write("                font-size: 11px;\n");
      out.write("                height: 25px;\n");
      out.write("                padding: 4px 12px;\n");
      out.write("                line-height: 1.42857;\n");
      out.write("            }\n");
      out.write("            .select2-container .select2-choice .select2-arrow {\n");
      out.write("                padding-top:6px;\n");
      out.write("                width: 25px;\n");
      out.write("            }\n");
      out.write("            .input-group-addon {\n");
      out.write("                padding: 4px 6px;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            td {\n");
      out.write("                vertical-align: middle !important;\n");
      out.write("            }\n");
      out.write("            #tableListPatient >thead > tr th:nth-child(1),\n");
      out.write("            #tableListPatient >tbody > tr td:nth-child(1){\n");
      out.write("                width: 3%!important;\n");
      out.write("            }\n");
      out.write("            #tableListPatient >thead > tr th:nth-child(2),\n");
      out.write("            #tableListPatient >tbody > tr td:nth-child(2){\n");
      out.write("                width: 8%!important;\n");
      out.write("            }\n");
      out.write("            #tableListPatient >thead > tr th:nth-child(3),\n");
      out.write("            #tableListPatient >tbody > tr td:nth-child(3){\n");
      out.write("                width: 8%!important;\n");
      out.write("            }\n");
      out.write("            #tableListPatient >thead > tr th:nth-child(4)\n");
      out.write("            {\n");
      out.write("                width: 8%!important;\n");
      out.write("            }\n");
      out.write("            #tableListPatient >tbody > tr td:nth-child(4){\n");
      out.write("                width: 8%!important;\n");
      out.write("                text-align: right\n");
      out.write("            }\n");
      out.write("            #tableListPatient >thead > tr th:nth-child(5){\n");
      out.write("                width: 12%!important;\n");
      out.write("            }\n");
      out.write("            #tableListPatient >tbody > tr td:nth-child(5){\n");
      out.write("                width: 12%!important;\n");
      out.write("                text-align: right\n");
      out.write("            }\n");
      out.write("            #tableListPatient >thead > tr th:nth-child(6)\n");
      out.write("            {\n");
      out.write("                width: 10%!important;\n");
      out.write("            }\n");
      out.write("            #tableListPatient >tbody > tr td:nth-child(6){\n");
      out.write("                width: 10%!important;\n");
      out.write("                text-align: right\n");
      out.write("            }\n");
      out.write("            #tableListPatient >thead > tr th:nth-child(7)\n");
      out.write("            {\n");
      out.write("                width: 10%!important;\n");
      out.write("            }\n");
      out.write("            #tableListPatient >tbody > tr td:nth-child(7){\n");
      out.write("                width: 10%!important;\n");
      out.write("                text-align: right\n");
      out.write("            }\n");
      out.write("            #tableListPatient >thead > tr th:nth-child(8),\n");
      out.write("            #tableListPatient >tbody > tr td:nth-child(8){\n");
      out.write("                width: 22%!important;\n");
      out.write("            }\n");
      out.write("            #tableListPatient >thead > tr th:nth-child(9),\n");
      out.write("            #tableListPatient >tbody > tr td:nth-child(9){\n");
      out.write("                width: 8%!important;\n");
      out.write("            }\n");
      out.write("            #tableListPatient >thead > tr th:nth-child(10),\n");
      out.write("            #tableListPatient >tbody > tr td:nth-child(10){\n");
      out.write("                width: 5%!important;\n");
      out.write("            }\n");
      out.write("            #tableListPatient >thead > tr th:nth-child(11),\n");
      out.write("            #tableListPatient >tbody > tr td:nth-child(11){\n");
      out.write("                width: 8%!important;\n");
      out.write("            }\n");
      out.write("            #tableListPatient >thead > tr th:nth-child(12),\n");
      out.write("            #tableListPatient >tbody > tr td:nth-child(12){\n");
      out.write("                width: 5%!important;\n");
      out.write("            }\n");
      out.write("            #tableListPatient  >tbody {\n");
      out.write("                flex: 1 1 auto;\n");
      out.write("                width: 100%;\n");
      out.write("                display: block;\n");
      out.write("                overflow-y: scroll;\n");
      out.write("                overflow-x: hidden;\n");
      out.write("                min-height: 20px;\n");
      out.write("                max-height: calc(100vh - 245px);\n");
      out.write("                height:auto !important;\n");
      out.write("            }\n");
      out.write("            #tableListPatient {\n");
      out.write("                display: flex;\n");
      out.write("                flex-flow: column;\n");
      out.write("                height: 100%;\n");
      out.write("                width: 100%;\n");
      out.write("            }\n");
      out.write("            #tableListPatient >thead, #tableListPatient >tbody tr {\n");
      out.write("                display: table;\n");
      out.write("                table-layout: fixed;\n");
      out.write("            }\n");
      out.write("            #tableListPatient >thead {\n");
      out.write("                /* head takes the height it requires, \n");
      out.write("                and it's not scaled when table is resized */\n");
      out.write("                width: calc(100% - 0.4em ) !important;\n");
      out.write("                flex: 0 0 auto;\n");
      out.write("            }\n");
      out.write("            #tableListPatient >tbody tr {\n");
      out.write("                width: 100%;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            #tableListPatient > tbody > tr > td,\n");
      out.write("            #tableListPatient > tbody > tr > th,\n");
      out.write("            #tableListPatient > tfoot > tr > td,\n");
      out.write("            #tableListPatient > tfoot > tr > th,\n");
      out.write("            #tableListPatient > thead > tr > td,\n");
      out.write("            #tableListPatient > thead > tr > th {\n");
      out.write("                padding: 3px 5px!important;\n");
      out.write("                font-size: 12px;\n");
      out.write("            }\n");
      out.write("            .btn.filtreActif{\n");
      out.write("                background-color: white;\n");
      out.write("                color: black;\n");
      out.write("                border-left-width: 5px;\n");
      out.write("                border-bottom-color: #0000003b;\n");
      out.write("                border-top-color: #0000003b;\n");
      out.write("                border-right-color: #0000003b;\n");
      out.write("                margin: 0px 2px!important;\n");
      out.write("                border-radius: 1px;\n");
      out.write("                box-sizing: border-box;\n");
      out.write("                width: calc(33.33% - 19px);\n");
      out.write("            }\n");
      out.write("            .btn.etatCli{\n");
      out.write("                background-color: white;\n");
      out.write("                color: black;\n");
      out.write("                border-left-width: 5px;\n");
      out.write("                border-bottom-color: #0000003b!important;\n");
      out.write("                border-top-color: #0000003b!important;\n");
      out.write("                border-right-color: #0000003b!important;\n");
      out.write("                margin: 0px 2px!important;\n");
      out.write("                border-radius: 1px;\n");
      out.write("                box-sizing: border-box;\n");
      out.write("                width: calc(17.73% - 19px);\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .widget-body{\n");
      out.write("                z-index: 0;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            #date_du{\n");
      out.write("                z-index: 0 !important;\n");
      out.write("            }\n");
      out.write("            #date_au{\n");
      out.write("                z-index: 0 !important;\n");
      out.write("            }\n");
      out.write("            #dateNaissRecherchePatient{\n");
      out.write("                z-index: 0 !important;\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("            \n");
      out.write("            #detailsFacture table thead > tr th:nth-child(1),\n");
      out.write("            #detailsFacture table tbody > tr td:nth-child(1){\n");
      out.write("                width: 5%!important;\n");
      out.write("            }\n");
      out.write("            #detailsFacture table thead > tr th:nth-child(2),\n");
      out.write("            #detailsFacture table tbody > tr td:nth-child(2){\n");
      out.write("                width: 10%!important;\n");
      out.write("            }\n");
      out.write("            #detailsFacture table thead > tr th:nth-child(3)\n");
      out.write("            {\n");
      out.write("                width: 10%!important;\n");
      out.write("            }\n");
      out.write("            #detailsFacture table tbody > tr td:nth-child(3){\n");
      out.write("                width: 15%!important;\n");
      out.write("                text-align: right;\n");
      out.write("            }\n");
      out.write("            #detailsFacture table thead > tr th:nth-child(4){\n");
      out.write("                width: 9%!important;\n");
      out.write("            }\n");
      out.write("            #detailsFacture table tbody > tr td:nth-child(4){\n");
      out.write("                width: 9%!important;\n");
      out.write("                text-align: right;\n");
      out.write("            }\n");
      out.write("            #detailsFacture table thead > tr th:nth-child(5)\n");
      out.write("            {\n");
      out.write("                width: 15%!important;\n");
      out.write("            }\n");
      out.write("            #detailsFacture table tbody > tr td:nth-child(5){\n");
      out.write("                width: 10%!important;\n");
      out.write("                text-align: right;\n");
      out.write("            }\n");
      out.write("            #detailsFacture table thead > tr th:nth-child(6)\n");
      out.write("            {\n");
      out.write("                width: 10%!important;\n");
      out.write("            }\n");
      out.write("            #detailsFacture table tbody > tr td:nth-child(6){\n");
      out.write("                width: 9%!important;\n");
      out.write("                text-align: right;\n");
      out.write("            }\n");
      out.write("            #detailsFacture table thead > tr th:nth-child(7),\n");
      out.write("            #detailsFacture table tbody > tr td:nth-child(7){\n");
      out.write("                width: 4%!important;\n");
      out.write("            }\n");
      out.write("            #detailsFacture  table tbody {\n");
      out.write("                flex: 1 1 auto;\n");
      out.write("                width: 100%;\n");
      out.write("                display: block;\n");
      out.write("                overflow-y: scroll;\n");
      out.write("                overflow-x: hidden;\n");
      out.write("                min-height: 20px;\n");
      out.write("                max-height: 167px;\n");
      out.write("                height:auto !important;\n");
      out.write("            }\n");
      out.write("            #detailsFacture table{\n");
      out.write("                /* display: flex;*/\n");
      out.write("                flex-flow: column;\n");
      out.write("                height: 100%;\n");
      out.write("                width: 100%;\n");
      out.write("            }\n");
      out.write("            #detailsFacture table thead, #detailsFacture table tbody tr {\n");
      out.write("                display: table;\n");
      out.write("                table-layout: fixed;\n");
      out.write("            }\n");
      out.write("            #detailsFacture table thead {\n");
      out.write("                /* head takes the height it requires, \n");
      out.write("                and it's not scaled when table is resized */\n");
      out.write("                width: calc(100% - 6px ) !important;\n");
      out.write("                flex: 0 0 auto;\n");
      out.write("            }\n");
      out.write("            #detailsFacture table tbody tr {\n");
      out.write("                width: 100%;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            #detailsFacture > tbody > tr > td,\n");
      out.write("            #detailsFacture > tbody > tr > th,\n");
      out.write("            #detailsFacture > tfoot > tr > td,\n");
      out.write("            #detailsFacture > tfoot > tr > th,\n");
      out.write("            #detailsFacture > thead > tr > td,\n");
      out.write("            #detailsFacture > thead > tr > th {\n");
      out.write("                padding: 5px;\n");
      out.write("                font-size: 12px;\n");
      out.write("            }\n");
      out.write("        </style>\n");
      out.write("    </head>\n");
      out.write("    <body class=\"styleCsys\" > \n");
      out.write("        <div class=\"modal fade screen\" id=\"modalAjoutRemise\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"false\" data-backdrop=\"static\" data-keyboard=\"false\">\n");
      out.write("            <div class=\"modal-dialog centre_screen\" style=\"width: 80%\">\n");
      out.write("                <div class=\"modal-content\"> \n");
      out.write("                    <div class=\"modal-header\" style=\"color: #1293b8;\">\n");
      out.write("                        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\"><i class=\"fa fa-times\"></i></button>\n");
      out.write("                        <h4 class=\"modal-title\">\n");
      out.write("                            <i style=\"font-size: 20px;\" id =\"modalIconpharmacie\" ></i> \n");
      out.write("                            <span id=\"labelTitre\">Saisie d'une Remise sur facture</span>\n");
      out.write("                        </h4>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"modal-body\" style='padding-bottom: 5px;'>\n");
      out.write("                        <div class=\"row\">\n");
      out.write("                            <div class=\"widget-body screen col-md-12\">\n");
      out.write("                                <fieldset>\n");
      out.write("                                    <div class=\"row\"> \n");
      out.write("                                        <div class=\"col-md-2  form-group \">\n");
      out.write("                                            <label class=\"form-label disabledHover \" for=\"simpleinput\"\n");
      out.write("                                                   >N° Dossier</label>\n");
      out.write("                                            <input disabled type=\"text\" id=\"numeroDossier\" class=\"form-control \"\n");
      out.write("                                                   aria-describedby=\"emailHelp\" data-i18n=\"[placeholder]pages.patient.ndossier\" required=\"\">\n");
      out.write("                                        </div>\n");
      out.write("\n");
      out.write("                                        <div class=\"col-md-2  form-group \">\n");
      out.write("                                            <label class=\"form-label disabledHover \" for=\"simpleinput\"\n");
      out.write("                                                   >Patient</label>\n");
      out.write("                                            <input disabled type=\"text\" id=\"patient\" class=\"form-control \" aria-describedby=\"emailHelp\"\n");
      out.write("                                                   data-i18n=\"[placeholder]pages.patient.nom\" required=\"\">\n");
      out.write("                                        </div>\n");
      out.write("\n");
      out.write("                                        <div class=\"col-md-2\" style=\"    padding-right: 0;\">\n");
      out.write("\n");
      out.write("                                            <label class=\"form-label disabledHover \" for=\"simpleinput\">Date d'admission\n");
      out.write("                                            </label>\n");
      out.write("                                            <div class=\"input-group\">\n");
      out.write("                                                <input disabled id=\"dateAdmission\" type=\"text\" class=\"form-control _date_deb_fin_filtre\"\n");
      out.write("                                                       data-mask=\"00/00/0000\" placeholder=\" Du\">\n");
      out.write("                                                <div class=\"input-group-append\">\n");
      out.write("                                                    <span class=\"input-group-text fs-xs\">\n");
      out.write("                                                        <i class=\"fal fa-calendar\"></i>\n");
      out.write("                                                    </span>\n");
      out.write("                                                </div>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"row \">\n");
      out.write("                                        <div class=\"col-md-2  form-group \">\n");
      out.write("                                            <label class=\"form-label disabledHover \" for=\"simpleinput\" >Médecin</label>\n");
      out.write("                                            <input disabled type=\"text\" id=\"medecinTrait\" class=\"form-control \" aria-describedby=\"emailHelp\"\n");
      out.write("                                                   data-i18n=\"[placeholder]pages.patient.medecin\" required=\"\">\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"col-md-2  form-group \">\n");
      out.write("                                            <label class=\"form-label disabledHover \" for=\"simpleinput\">Chambre</label>\n");
      out.write("                                            <input disabled type=\"text\" id=\"NumChambre\" class=\"form-control \" aria-describedby=\"emailHelp\"\n");
      out.write("                                                   data-i18n=\"[placeholder]pages.patient.chambre\" required=\"\">\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"col-md-3  form-group \">\n");
      out.write("                                            <label class=\"form-label disabledHover \" for=\"simpleinput\"\n");
      out.write("                                                   >Motif</label>\n");
      out.write("                                            <input disabled type=\"text\" id=\"desMotif\" class=\"form-control \" aria-describedby=\"emailHelp\"\n");
      out.write("                                                   required=\"\">NumSer\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"col-md-3  form-group \">\n");
      out.write("                                            <label class=\"form-label disabledHover \" for=\"simpleinput\">Organisme</label>\n");
      out.write("                                            <input disabled type=\"text\" id=\"organisme\" class=\"form-control \" aria-describedby=\"emailHelp\"\n");
      out.write("                                                   required=\"\">\n");
      out.write("                                        </div>\n");
      out.write("\n");
      out.write("                                        <div class=\"col-md-2  form-group \">\n");
      out.write("                                            <label class=\"form-label disabledHover \" for=\"simpleinput\"\n");
      out.write("                                                   >Nature admission</label>\n");
      out.write("                                            <input disabled type=\"text\" id=\"natureAdm\" class=\"form-control \" aria-describedby=\"emailHelp\"\n");
      out.write("                                                   required=\"\">\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"row \">\n");
      out.write("                                        <div class=\"frame-wrap\">\n");
      out.write("                                            <div class=\"custom-control custom-radio custom-control-inline\">\n");
      out.write("                                                <input type=\"radio\" class=\"custom-control-input\" id=\"ParFamille\" name=\"etatGroup\"\n");
      out.write("                                                       checked=\"\">\n");
      out.write("                                                <label class=\"custom-control-label\" for=\"ParFamille\">Par Famille</label>\n");
      out.write("                                            </div>\n");
      out.write("                                            <div class=\"custom-control custom-radio custom-control-inline\">\n");
      out.write("                                                <input type=\"radio\" class=\"custom-control-input\" id=\"ParPrestation\" name=\"etatGroup\">\n");
      out.write("                                                <label class=\"custom-control-label\" for=\"ParPrestation\">ParPrestation</label>\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"row \">\n");
      out.write("                                        <div class=\" col-md-12\" id=\"detailsFacture\" >\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-md-12 row\" style=\"height: calc(100vh - 10px );\">\n");
      out.write("                            <div class=\"col-md-8 panel\" style=\"height: calc(100vh - 30px );\">\n");
      out.write("                                <div class=\"row \">\n");
      out.write("                                    <div class=\"col-md-4  form-group \">\n");
      out.write("                                        <label class=\"form-label disabledHover \" for=\"simpleinput\">Remise\n");
      out.write("                                            autorisée\n");
      out.write("                                            par</label>\n");
      out.write("                                        <select id=\"selectRemiseAutoris\" class=\"form-control select2\" required></select>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"col-md-8  form-group \">\n");
      out.write("                                        <label class=\"form-label disabledHover \" for=\"simpleinput\">Motif</label>\n");
      out.write("                                        <textarea class=\"form-control \" id=\"motif\" rows=\"3\" cols=\"50\">\n");
      out.write("                                        </textarea>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"row \">\n");
      out.write("                                    <div class=\"col-md-4  form-group \">\n");
      out.write("                                        <div class=\"row\">\n");
      out.write("                                            <label class=\"form-label disabledHover \" for=\"simpleinput\">Confirmé\n");
      out.write("                                                par</label>\n");
      out.write("                                            <select id=\"selectRemiseConfirme\" class=\"form-control select2\" style=\"  margin-top: -29px;\"\n");
      out.write("                                                    required></select>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <table id=\"dt-demandeRemise\" class=\"table m-1 table-bordered table-hover table-striped w-100 table-sm\">\n");
      out.write("                                </table>\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"col-md-4 panel\" style=\"height: calc(100vh - 30px );\">\n");
      out.write("                                <div class=\"row\">\n");
      out.write("                                    <div class=\"col-md-12 form-group \">\n");
      out.write("                                        <label class=\"form-label disabledHover \" for=\"simpleinput\">Remise\n");
      out.write("                                            clinique</label>\n");
      out.write("                                        <input disabled type=\"text\" id=\"remiseClinique\" class=\"form-control txtRight \"\n");
      out.write("                                               aria-describedby=\"emailHelp\" required=\"\">\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"row\">\n");
      out.write("                                    <div class=\"col-md-12 form-group \">\n");
      out.write("                                        <label class=\"form-label disabledHover \" for=\"simpleinput\">Remise\n");
      out.write("                                            honoraires</label>\n");
      out.write("                                        <input disabled type=\"text\" id=\"remiseHonoraire\" class=\"form-control txtRight \"\n");
      out.write("                                               aria-describedby=\"emailHelp\" required=\"\">\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"row\">\n");
      out.write("                                    <div class=\"col-md-12 form-group \">\n");
      out.write("                                        <label class=\"form-label disabledHover \" for=\"simpleinput\">Remise\n");
      out.write("                                            TTC</label>\n");
      out.write("                                        <input disabled type=\"text\" id=\"remiseTTC\" class=\"form-control txtRight \"\n");
      out.write("                                               aria-describedby=\"emailHelp\" required=\"\">\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"row\">\n");
      out.write("                                    <div class=\"col-md-12  form-group \">\n");
      out.write("                                        <label class=\"form-label disabledHover \" for=\"simpleinput\">Budget des\n");
      out.write("                                            remises</label>\n");
      out.write("                                        <input disabled type=\"text\" id=\"budgetRemise\" class=\"form-control txtRight\"\n");
      out.write("                                               aria-describedby=\"emailHelp\" required=\"\">\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"row\">\n");
      out.write("                                    <div class=\"col-md-12  form-group \">\n");
      out.write("                                        <label class=\"form-label disabledHover \" for=\"simpleinput\">solde du\n");
      out.write("                                            budget</label>\n");
      out.write("                                        <input disabled type=\"text\" id=\"soldeBudget\" class=\"form-control txtRight\"\n");
      out.write("                                               aria-describedby=\"emailHelp\" required=\"\">\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"row\">\n");
      out.write("                                    <div class=\"col-md-12  form-group \">\n");
      out.write("                                        <label class=\"form-label disabledHover \" for=\"simpleinput\">Taux\n");
      out.write("                                            maximum</label>\n");
      out.write("                                        <input disabled type=\"text\" id=\"tauxMaximum\" class=\"form-control txtRight \"\n");
      out.write("                                               aria-describedby=\"emailHelp\" required=\"\">\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <footer class=\"Csysfooterdialog\">\n");
      out.write("                        <div class=\"\">\n");
      out.write("                            <button type=\"button\" class=\"btn btn-primary valider\" id=\"validerRemise\"\n");
      out.write("                                    data-i18n=\"commons.valider\"></button>\n");
      out.write("                            <button type=\"button\" class=\"btn btn-primary delete\" id=\"historique_remise\"><i\n");
      out.write("                                    class=\"fal fa-rectangle-history\"></i>\n");
      out.write("                                Historique de la remise </span></button>\n");
      out.write("                            <button type=\"button\" onclick=\"CloseWindow();\"\n");
      out.write("                                    class=\"btn btn-secondary fermerAvance waves-effect waves-themed  fw-400 ml-auto mr-2\"\n");
      out.write("                                    data-dismiss=\"modal\" data-i18n=\"commons.annuler\">Fermer</button>\n");
      out.write("                        </div>\n");
      out.write("                    </footer>\n");
      out.write("                </div>\n");
      out.write("            </div>     \n");
      out.write("        </div>\n");
      out.write("        <!--{{!-- HISTORIQUE --}}-->\n");
      out.write("        <div class=\"modal fade\" id=\"modalHistorique\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\n");
      out.write("            <div class=\"modal-dialog modal-xl\" role=\"document\" style=\"max-width: 80%;\">\n");
      out.write("                <div class=\"modal-content\">\n");
      out.write("                    <div class=\"modal-header\">\n");
      out.write("                        <h3 class=\"modal-title\">Historiques Remise</h3>\n");
      out.write("                        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("                            <span aria-hidden=\"true\"><i class=\"fal fa-times\"></i></span>\n");
      out.write("                        </button>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"modal-body\">\n");
      out.write("                        <div class=\"panel-container show\"></div>\n");
      out.write("                        <div id=\"panel-1\" class=\"panel\">\n");
      out.write("                            <div class=\"row\">\n");
      out.write("                                <div class=\"col-md-12\">\n");
      out.write("                                    <div class=\"fieldset1\">\n");
      out.write("                                        <div class=\"legend\" data-i18n=\"pages.nouveaupatient.info\">\n");
      out.write("                                            Patient\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"row\">\n");
      out.write("                                            <div class=\"col-md-3  form-group espacement\">\n");
      out.write("                                                <label class=\"form-label disabledHover \" for=\"simpleinput\"\n");
      out.write("                                                       data-i18n=\"pages.patient.identifiant\">Identifiant </label>\n");
      out.write("                                                <input disabled type=\"text\" id=\"identifiantHist\"\n");
      out.write("                                                       class=\"form-control form-controladm\" aria-describedby=\"emailHelp\"\n");
      out.write("                                                       autocomplete=\"off\" data-i18n=\"[placeholder]pages.patient.identifiant\"\n");
      out.write("                                                       placeholder=\"Identifiant \">\n");
      out.write("                                            </div>\n");
      out.write("                                            <div class=\"col-md-5  form-group espacement\">\n");
      out.write("                                                <label class=\"form-label disabledHover \" for=\"simpleinput\"\n");
      out.write("                                                       data-i18n=\"pages.patient.nom\">Nom</label>\n");
      out.write("                                                <input disabled type=\"text\" id=\"patientHist\"\n");
      out.write("                                                       class=\"form-control form-controladm\" aria-describedby=\"emailHelp\"\n");
      out.write("                                                       autocomplete=\"off\" data-i18n=\"[placeholder]pages.patient.nom\"\n");
      out.write("                                                       placeholder=\"Nom\">\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"row\">\n");
      out.write("                        <div class=\"col-xl-12\">\n");
      out.write("                            <table id=\"dt-historique\" class=\"table table-bordered table-hover table-striped w-100 table-sm\">\n");
      out.write("                            </table>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <footer class=\"Csysfooterdialog\">\n");
      out.write("                        <div>\n");
      out.write("                            <button type=\"button\" onclick=\"CloseWindowHistorique();\"\n");
      out.write("                                    class=\"btn btn-secondary fermerAvance waves-effect waves-themed  fw-400 ml-auto mr-2\"\n");
      out.write("                                    data-dismiss=\"modal\" data-i18n=\"commons.annuler\">Fermer</button>\n");
      out.write("                        </div>\n");
      out.write("                    </footer>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("        <style>\n");
      out.write("            [id^=\"drag\"]{\n");
      out.write("                width: 6%;\n");
      out.write("                height: 40px;\n");
      out.write("                margin: 0.5%;\n");
      out.write("                display: inline-block;\n");
      out.write("                color: white;\n");
      out.write("                border-radius: 0.75em;\n");
      out.write("                padding: 1.3%;\n");
      out.write("                font-weight: bolder;\n");
      out.write("                -webkit-transform: translate(0px, 0px);\n");
      out.write("                transform: translate(0px, 0px);\n");
      out.write("            }\n");
      out.write("            ul.tabs-left{\n");
      out.write("                overflow-y: scroll;\n");
      out.write("                max-height: 450px;\n");
      out.write("                overflow-x: hidden;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            #drag-me::before {\n");
      out.write("                content: \"#\" attr(id);\n");
      out.write("                font-weight: bold;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            .select2-container .select2-choice>.select2-chosen{\n");
      out.write("                color: black;\n");
      out.write("            }\n");
      out.write("        </style>\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "EditionModal.jsp", out, false);
      out.write("       \n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "js_declare.jsp", out, false);
      out.write("\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "EditionSessionExpire.jsp", out, false);
      out.write("\n");
      out.write("        <script>\n");
      out.write("            var url_base = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url_base}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\n");
      out.write("            var idModule = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${idModule}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\n");
      out.write("            var url_base_access = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url_base_access}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\n");
      out.write("            var currencyScale = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${currencyScale}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\n");
      out.write("            var url_base_fichier_base = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url_base_fichier_base}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\n");
      out.write("            var numRecept = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${numRecept}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\n");
      out.write("        </script>        \n");
      out.write("        <script src=\"body_page_js/remise_facture_function.js?version=");
      out.print(date);
      out.write("\"></script>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_spring_005feval_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:eval
    org.springframework.web.servlet.tags.EvalTag _jspx_th_spring_005feval_005f0 = (org.springframework.web.servlet.tags.EvalTag) _005fjspx_005ftagPool_005fspring_005feval_0026_005fvar_005fexpression_005fnobody.get(org.springframework.web.servlet.tags.EvalTag.class);
    boolean _jspx_th_spring_005feval_005f0_reused = false;
    try {
      _jspx_th_spring_005feval_005f0.setPageContext(_jspx_page_context);
      _jspx_th_spring_005feval_005f0.setParent(null);
      // /WEB-INF/body_page/remise_facture.jsp(12,0) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005feval_005f0.setVar("url_base");
      // /WEB-INF/body_page/remise_facture.jsp(12,0) name = expression type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005feval_005f0.setExpression("@environment.url_base");
      int[] _jspx_push_body_count_spring_005feval_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005feval_005f0 = _jspx_th_spring_005feval_005f0.doStartTag();
        if (_jspx_th_spring_005feval_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005feval_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005feval_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005feval_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005feval_0026_005fvar_005fexpression_005fnobody.reuse(_jspx_th_spring_005feval_005f0);
      _jspx_th_spring_005feval_005f0_reused = true;
    } finally {
      if (!_jspx_th_spring_005feval_005f0_reused) {
        _jspx_th_spring_005feval_005f0.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_spring_005feval_005f0);
      }
    }
    return false;
  }

  private boolean _jspx_meth_spring_005feval_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:eval
    org.springframework.web.servlet.tags.EvalTag _jspx_th_spring_005feval_005f1 = (org.springframework.web.servlet.tags.EvalTag) _005fjspx_005ftagPool_005fspring_005feval_0026_005fvar_005fexpression_005fnobody.get(org.springframework.web.servlet.tags.EvalTag.class);
    boolean _jspx_th_spring_005feval_005f1_reused = false;
    try {
      _jspx_th_spring_005feval_005f1.setPageContext(_jspx_page_context);
      _jspx_th_spring_005feval_005f1.setParent(null);
      // /WEB-INF/body_page/remise_facture.jsp(13,0) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005feval_005f1.setVar("idModule");
      // /WEB-INF/body_page/remise_facture.jsp(13,0) name = expression type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005feval_005f1.setExpression("@environment.idModule");
      int[] _jspx_push_body_count_spring_005feval_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005feval_005f1 = _jspx_th_spring_005feval_005f1.doStartTag();
        if (_jspx_th_spring_005feval_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005feval_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005feval_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005feval_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005feval_0026_005fvar_005fexpression_005fnobody.reuse(_jspx_th_spring_005feval_005f1);
      _jspx_th_spring_005feval_005f1_reused = true;
    } finally {
      if (!_jspx_th_spring_005feval_005f1_reused) {
        _jspx_th_spring_005feval_005f1.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_spring_005feval_005f1);
      }
    }
    return false;
  }

  private boolean _jspx_meth_spring_005feval_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:eval
    org.springframework.web.servlet.tags.EvalTag _jspx_th_spring_005feval_005f2 = (org.springframework.web.servlet.tags.EvalTag) _005fjspx_005ftagPool_005fspring_005feval_0026_005fvar_005fexpression_005fnobody.get(org.springframework.web.servlet.tags.EvalTag.class);
    boolean _jspx_th_spring_005feval_005f2_reused = false;
    try {
      _jspx_th_spring_005feval_005f2.setPageContext(_jspx_page_context);
      _jspx_th_spring_005feval_005f2.setParent(null);
      // /WEB-INF/body_page/remise_facture.jsp(14,0) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005feval_005f2.setVar("url_base_access");
      // /WEB-INF/body_page/remise_facture.jsp(14,0) name = expression type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005feval_005f2.setExpression("@environment.url_base_access");
      int[] _jspx_push_body_count_spring_005feval_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005feval_005f2 = _jspx_th_spring_005feval_005f2.doStartTag();
        if (_jspx_th_spring_005feval_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005feval_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005feval_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005feval_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005feval_0026_005fvar_005fexpression_005fnobody.reuse(_jspx_th_spring_005feval_005f2);
      _jspx_th_spring_005feval_005f2_reused = true;
    } finally {
      if (!_jspx_th_spring_005feval_005f2_reused) {
        _jspx_th_spring_005feval_005f2.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_spring_005feval_005f2);
      }
    }
    return false;
  }

  private boolean _jspx_meth_spring_005feval_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:eval
    org.springframework.web.servlet.tags.EvalTag _jspx_th_spring_005feval_005f3 = (org.springframework.web.servlet.tags.EvalTag) _005fjspx_005ftagPool_005fspring_005feval_0026_005fvar_005fexpression_005fnobody.get(org.springframework.web.servlet.tags.EvalTag.class);
    boolean _jspx_th_spring_005feval_005f3_reused = false;
    try {
      _jspx_th_spring_005feval_005f3.setPageContext(_jspx_page_context);
      _jspx_th_spring_005feval_005f3.setParent(null);
      // /WEB-INF/body_page/remise_facture.jsp(15,0) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005feval_005f3.setVar("currencyScale");
      // /WEB-INF/body_page/remise_facture.jsp(15,0) name = expression type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005feval_005f3.setExpression("@environment.currencyScale");
      int[] _jspx_push_body_count_spring_005feval_005f3 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005feval_005f3 = _jspx_th_spring_005feval_005f3.doStartTag();
        if (_jspx_th_spring_005feval_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005feval_005f3[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005feval_005f3.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005feval_005f3.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005feval_0026_005fvar_005fexpression_005fnobody.reuse(_jspx_th_spring_005feval_005f3);
      _jspx_th_spring_005feval_005f3_reused = true;
    } finally {
      if (!_jspx_th_spring_005feval_005f3_reused) {
        _jspx_th_spring_005feval_005f3.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_spring_005feval_005f3);
      }
    }
    return false;
  }

  private boolean _jspx_meth_spring_005feval_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:eval
    org.springframework.web.servlet.tags.EvalTag _jspx_th_spring_005feval_005f4 = (org.springframework.web.servlet.tags.EvalTag) _005fjspx_005ftagPool_005fspring_005feval_0026_005fvar_005fexpression_005fnobody.get(org.springframework.web.servlet.tags.EvalTag.class);
    boolean _jspx_th_spring_005feval_005f4_reused = false;
    try {
      _jspx_th_spring_005feval_005f4.setPageContext(_jspx_page_context);
      _jspx_th_spring_005feval_005f4.setParent(null);
      // /WEB-INF/body_page/remise_facture.jsp(16,0) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005feval_005f4.setVar("url_base_fichier_base");
      // /WEB-INF/body_page/remise_facture.jsp(16,0) name = expression type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005feval_005f4.setExpression("@environment.url_base_fichier_base");
      int[] _jspx_push_body_count_spring_005feval_005f4 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005feval_005f4 = _jspx_th_spring_005feval_005f4.doStartTag();
        if (_jspx_th_spring_005feval_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005feval_005f4[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005feval_005f4.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005feval_005f4.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005feval_0026_005fvar_005fexpression_005fnobody.reuse(_jspx_th_spring_005feval_005f4);
      _jspx_th_spring_005feval_005f4_reused = true;
    } finally {
      if (!_jspx_th_spring_005feval_005f4_reused) {
        _jspx_th_spring_005feval_005f4.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_spring_005feval_005f4);
      }
    }
    return false;
  }

  private boolean _jspx_meth_spring_005feval_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:eval
    org.springframework.web.servlet.tags.EvalTag _jspx_th_spring_005feval_005f5 = (org.springframework.web.servlet.tags.EvalTag) _005fjspx_005ftagPool_005fspring_005feval_0026_005fvar_005fexpression_005fnobody.get(org.springframework.web.servlet.tags.EvalTag.class);
    boolean _jspx_th_spring_005feval_005f5_reused = false;
    try {
      _jspx_th_spring_005feval_005f5.setPageContext(_jspx_page_context);
      _jspx_th_spring_005feval_005f5.setParent(null);
      // /WEB-INF/body_page/remise_facture.jsp(17,0) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005feval_005f5.setVar("numRecept");
      // /WEB-INF/body_page/remise_facture.jsp(17,0) name = expression type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005feval_005f5.setExpression("@environment.numRecept");
      int[] _jspx_push_body_count_spring_005feval_005f5 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005feval_005f5 = _jspx_th_spring_005feval_005f5.doStartTag();
        if (_jspx_th_spring_005feval_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005feval_005f5[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005feval_005f5.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005feval_005f5.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005feval_0026_005fvar_005fexpression_005fnobody.reuse(_jspx_th_spring_005feval_005f5);
      _jspx_th_spring_005feval_005f5_reused = true;
    } finally {
      if (!_jspx_th_spring_005feval_005f5_reused) {
        _jspx_th_spring_005feval_005f5.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_spring_005feval_005f5);
      }
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f0 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    boolean _jspx_th_spring_005fmessage_005f0_reused = false;
    try {
      _jspx_th_spring_005fmessage_005f0.setPageContext(_jspx_page_context);
      _jspx_th_spring_005fmessage_005f0.setParent(null);
      // /WEB-INF/body_page/remise_facture.jsp(23,15) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005fmessage_005f0.setCode("fb.Acceuil.Patient");
      int[] _jspx_push_body_count_spring_005fmessage_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005fmessage_005f0 = _jspx_th_spring_005fmessage_005f0.doStartTag();
        if (_jspx_th_spring_005fmessage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005fmessage_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005fmessage_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005fmessage_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f0);
      _jspx_th_spring_005fmessage_005f0_reused = true;
    } finally {
      if (!_jspx_th_spring_005fmessage_005f0_reused) {
        _jspx_th_spring_005fmessage_005f0.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_spring_005fmessage_005f0);
      }
    }
    return false;
  }
}
